Repository clockworklabs/SpacetimeDB, pull requests merged in 2023-11, with the labels that each got.

#516 Add OptIn serialization attribute for C# generated types
  crates/cli/src/subcommands/generate/csharp.rs
Labels: release-0.7.3

#487 fix benchmarks run on master
  .github/workflows/benchmarks.yml
Labels: release-any

#495 Refactor commit encoding / decoding
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/db/commit_log.rs
  crates/core/src/db/messages/commit.rs
  crates/core/src/db/messages/transaction.rs
  crates/core/src/db/messages/write.rs
Labels: release-0.8

#500 Added multi column index usage to the rust-wasm-test module
  crates/testing/tests/standalone_integration_test.rs
  modules/rust-wasm-test/src/lib.rs
Labels: release-0.7.2, release-0.7.3

#530 Track instance_queue_length by reducer
  crates/core/src/host/module_host.rs
  crates/core/src/util/lending_pool.rs
  crates/core/src/worker_metrics/mod.rs
Labels: release-0.7.3

#496 core: Track the number of bytes read when iterating over the WAL
  crates/core/src/db/commit_log.rs
  crates/core/src/db/message_log.rs
Labels: release-0.8

#534 Capture logs in integration tests
  Cargo.lock
  crates/testing/Cargo.toml
  crates/testing/tests/standalone_integration_test.rs
Labels: release-any

#540 Downgrade a log line from info to debug
  crates/core/src/host/wasmer/wasm_instance_env.rs
Labels: release-0.7.3

#539 `InstanceEnv::delete_by_col_eq`: return `u32` instead of `NonZeroU32`
  crates/core/src/host/instance_env.rs
  crates/core/src/host/wasmer/wasm_instance_env.rs
Labels: release-0.7.3

#526 core: Add truncation to message log
  crates/core/src/db/message_log.rs
Labels: release-0.8

#538 Add integration test for the query macro
  crates/core/src/host/mod.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/rust-wasm-test/src/lib.rs
Labels: release-0.8

#544 Desparse Tar Files When Building
  .github/workflows/linux-build.yml
  .github/workflows/macos-build.yml
Labels: release-0.7.4

#439 Refactoring IDs for system objects
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/src/spacetime_module.rs
  crates/bench/src/spacetime_raw.rs
  crates/bench/src/sqlite.rs
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/cli/Cargo.toml
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/python.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/core/src/db/commit_log.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmer/wasm_instance_env.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/lib/Cargo.toml
  crates/lib/src/identity.rs
  crates/lib/src/lib.rs
  crates/primitives/src/attr.rs
  crates/primitives/src/lib.rs
  crates/sats/src/db/attr.rs
  crates/sats/src/db/def.rs
  crates/sats/src/lib.rs
  crates/sats/src/product_value.rs
  crates/vm/src/expr.rs
Labels: release-0.8, abi-break

#561 Move 'constraints' markers to primitive and fix incompatibility with deploy
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/python.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/sql/ast.rs
  crates/primitives/src/attr.rs
  crates/primitives/src/lib.rs
  crates/sats/src/db/def.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/rust-wasm-test/src/lib.rs
Labels: abi-break

#568 core: Refine panic message when decoding fails during replay
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
Labels: release-0.7.4

#457 Switch from wasmer to wasmtime
  Cargo.lock
  Cargo.toml
  crates/cli/src/subcommands/publish.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/energy.rs
  crates/core/Cargo.toml
  crates/core/src/control_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmer/mod.rs
  crates/core/src/host/wasmer/opcode_cost.rs
  crates/core/src/host/wasmer/wasmer_module.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/core/src/messages/control_db.rs
  crates/standalone/src/energy_monitor.rs
  crates/standalone/src/lib.rs
Labels: release-0.8

#575 core: Only write actual large objects to odb
  crates/core/src/db/commit_log.rs
Labels: release-0.8

#604 Hotfix for log replay bug, fix type for constraints column
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/system_tables.rs
Labels: bug, release-0.8

#521 Format binary data as hex in sql/satn
  crates/core/src/control_db/tests.rs
  crates/lib/src/identity.rs
  crates/lib/tests/serde.rs
  crates/lib/tests/snapshots/serde__json_mappings-2.snap
  crates/lib/tests/snapshots/serde__json_mappings.snap
  crates/sats/src/algebraic_value.rs
  crates/sats/src/satn.rs
  test/tests/sql-format.sh
Labels: release-0.8

#587 Move to .NET 8 WASI support
  .github/workflows/ci.yml
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/RawBindings.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/bindings-csharp/Runtime/bindings.c
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
  crates/bindings-csharp/Runtime/driver.h
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  crates/cli/src/tasks/csharp.rs
  modules/sdk-test-connect-disconnect-cs/StdbModule.csproj
  modules/spacetimedb-quickstart-cs/StdbModule.csproj
Labels: release-0.8, abi-break
