Repository clockworklabs/SpacetimeDB, pull requests merged in 2023-12, with the labels that each got.

#596 Refactoring bootstrapping and adding full support for constraints & multi-column indexes
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/src/spacetime_raw.rs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Codegen/Type.cs
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/RawBindings.cs
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/python.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/core/src/control_db.rs
  crates/core/src/db/datastore/locking_tx_datastore/btree_index.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/locking_tx_datastore/table.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/error.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/query.rs
  crates/core/src/vm.rs
  crates/lib/src/lib.rs
  crates/primitives/src/attr.rs
  crates/sats/src/buffer.rs
  crates/sats/src/data_key.rs
  crates/sats/src/db/def.rs
  crates/sats/src/db/error.rs
  crates/sats/src/de/impls.rs
  crates/sats/src/product_value.rs
  crates/sats/src/relation.rs
  crates/sats/src/ser/impls.rs
  crates/vm/src/dsl.rs
  crates/vm/src/eval.rs
  crates/vm/src/expr.rs
  crates/vm/src/typecheck.rs
  modules/spacetimedb-quickstart/Cargo.toml
Labels: release-0.8, abi-break

#586 Support arbitrary RHS in C# Query
  Cargo.lock
  crates/bench/src/spacetime_module.rs
  crates/bindings-csharp/Runtime/Filter.cs
  crates/core/src/database_logger.rs
  crates/testing/Cargo.toml
  crates/testing/src/modules.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/spacetimedb-quickstart-cs/Lib.cs
  modules/spacetimedb-quickstart/src/lib.rs
Labels: release-0.8

#628 C#: don't show "Extracting..." message if already unpacked
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
Labels: release-0.8

#599 Added RWLock on committed state
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
Labels: release-0.8

#647 Fixes for performance drop related to missing index selection
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/error.rs
  crates/core/src/sql/ast.rs
  crates/sats/src/db/def.rs
  crates/sats/src/db/error.rs
Labels: bug

#640 [CI] Merge docker images from multiple platforms
  .github/workflows/docker.yml
  tools/merge-docker-images.sh
Labels: release-0.8

#603 Improve TypeScript generated code (fixes and improvements)
  crates/cli/src/subcommands/generate/typescript.rs
Labels: release-0.8

#693 Delete Files Flag for Generate Command
  crates/cli/src/subcommands/generate/mod.rs
Labels: release-any
