Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-10, with the labels that each got.

#1774 CLI - `spacetime generate` always deletes stale files
  crates/cli/src/subcommands/generate/mod.rs
Labels: api-break, release-0.12

#1758 [C#] Migrate bench-cs to the new API
  .github/workflows/ci.yml
  crates/bindings-csharp/SpacetimeSharpSATS.sln
  modules/benchmarks-cs/benchmarks-cs.csproj
  modules/benchmarks-cs/circles.cs
  modules/benchmarks-cs/ia_loop.cs
  modules/benchmarks-cs/synthetic.cs
  smoketests/tests/csharp_module.py
Labels: release-any

#1711 Filter out deps that only is added to keccack on arm that broke local testing
  crates/bindings/tests/deps.rs
Labels: release-any, bugfix

#1729 [C#] [Reducers] Implement new context fields, enum-based kinds, validation
  crates/bindings-csharp/BSATN.Codegen/Diag.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#InAnotherNamespace.TestDuplicateTableName.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.InAnotherNamespace.TestDuplicateReducerName.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestDuplicateReducerKind1.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestDuplicateReducerKind2.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestDuplicateReducerName.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestIncompatibleScheduleReducer.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestReducerReturnType.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.TestReducerWithoutContext.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestAutoIncNotInteger.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestDuplicateTableName.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestIncompatibleSchedule.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestUniqueNotEquatable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Test.NestingNamespaces.AndClasses.InsertData2.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Diag.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
Labels: api-break, release-0.12

#1777 Remove abi functions that are no longer needed
  crates/bindings-sys/src/lib.rs
  crates/bindings/src/table.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
Labels: release-0.12

#1775 [bindings-csharp] Upgrade WASI SDK & enable for ARM64
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
Labels: release-0.12

#1778 commitlog: Return commit info
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/segment.rs
Labels: release-any, no runtime change

#1782 More obsolete cleanup
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/bindings-csharp/Runtime/bindings.c
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
  crates/core/src/host/instance_env.rs
  crates/lib/src/filter.rs
  crates/lib/src/lib.rs
Labels: release-0.12

#1776 Implemented TypeScript SDK proposal codegen
  crates/cli/src/subcommands/generate/code_indenter.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/src/subcommands/generate/util.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  modules/rust-wasm-test/src/lib.rs
Labels: release-0.12

#1793 Fix a rustfmt issue that occurs during rust client code generation
  crates/cli/src/subcommands/generate/mod.rs
Labels: release-0.12

#1792 [C#] [NFC] Some tweaks to the diagnostic tests
  .gitattributes
  crates/bindings-csharp/Codegen.Tests/TestInit.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/.gitattributes
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.OnReducerWithReservedPrefix.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#Reducers.__ReducerWithReservedPrefix.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestIncompatibleSchedule.TestIncompatibleScheduleReducer.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Type.verified.txt
  crates/bindings-csharp/Runtime/Internal/.gitattributes
Labels: release-any, no runtime change

#1800 Small fixes to TypeScript codegen
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
Labels: release-0.12

#1707 c# client generate
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestAutoIncNotInteger.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestIncompatibleSchedule.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestUniqueNotEquatable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#BTreeMultiColumn.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#BTreeViews.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#MultiTableRow.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Diag.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Exceptions.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawColumnDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawReducerDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScheduleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScopedTypeNameV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTypeDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawUniqueConstraintDataV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/ReducerDef.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableDesc.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TypeAlias.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/Typespace.cs
  crates/bindings-csharp/Runtime/Internal/Bounds.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/IIndex.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/Internal/Timing.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/bindings.c
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/sdk/tests/test.rs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
  smoketests/tests/namespaces.py
Labels: abi-break, release-0.12

#1805 CLI - `spacetime upgrade` takes `--yes` instead of deprecated `--force`
  crates/cli/src/subcommands/upgrade.rs
Labels: release-any, CLI only, release-1.0, api-break

#1834 Add CODEOWNERS for CLI crate
  .github/CODEOWNERS
Labels: release-any

#1746 Adding the system table for row level security
  Cargo.lock
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawRowLevelSecurityDefV9.cs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/error.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/schema/Cargo.toml
  crates/schema/src/def.rs
  crates/schema/src/def/validate/v8.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
  crates/schema/src/schema.rs
Labels: abi-break, release-1.0

#766 Energy metering for persistent memory usage
  Cargo.lock
  Cargo.toml
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/client-api-messages/src/energy.rs
  crates/client-api/src/routes/prometheus.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/sequence.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/relational_operators.rs
  crates/core/src/energy.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/replica_context.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/subscription.rs
  crates/data-structures/Cargo.toml
  crates/data-structures/src/map.rs
  crates/lib/src/relation.rs
  crates/primitives/src/col_list.rs
  crates/schema/src/type_for_generate.rs
  crates/sdk/src/spacetime_module.rs
  crates/standalone/src/energy_monitor.rs
  crates/table/src/bflatn_to_bsatn_fast_path.rs
  crates/table/src/blob_store.rs
  crates/table/src/btree_index.rs
  crates/table/src/btree_index/multimap.rs
  crates/table/src/fixed_bit_set.rs
  crates/table/src/indexes.rs
  crates/table/src/layout.rs
  crates/table/src/lib.rs
  crates/table/src/memory_usage.rs
  crates/table/src/page.rs
  crates/table/src/pages.rs
  crates/table/src/pointer_map.rs
  crates/table/src/row_type_visitor.rs
  crates/table/src/table.rs
  crates/testing/src/sdk.rs
  crates/vm/src/expr.rs
  crates/vm/src/rel_ops.rs
Labels: energy-tracking, breaks library compatibility, release-1.0

#1216 Improve bindings diagnostics and add ui tests
  Cargo.lock
  Cargo.toml
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/module.rs
  crates/bindings/Cargo.toml
  crates/bindings/src/rt.rs
  crates/bindings/tests/ui.rs
  crates/bindings/tests/ui/reducers.rs
  crates/bindings/tests/ui/reducers.stderr
  crates/bindings/tests/ui/tables.rs
  crates/bindings/tests/ui/tables.stderr
  crates/sats/src/typespace.rs
Labels: release-any

#1849 RLS: Adding a new filter! macro
  Cargo.lock
  crates/bindings-macro/Cargo.toml
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/core/src/db/update.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/mod.rs
  crates/core/src/sql/parser.rs
  crates/expr/src/errors.rs
  crates/expr/src/expr.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/schema/src/auto_migrate.rs
  modules/sdk-test/src/lib.rs
  smoketests/tests/auto_migration.py
Labels: enhancement, release-1.0

#1845 CLI - Stabilize `spacetime server` subcommands
  crates/cli/src/subcommands/server.rs
  smoketests/__init__.py
  smoketests/tests/servers.py
Labels: release-any, CLI only, release-1.0, api-break

#1616 Redefine Address as `U128` + `Identity` and Hash as `U256`
  Cargo.toml
  crates/bench/src/lib.rs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/bindings/src/rt.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/core/src/client/messages.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/type_check.rs
  crates/lib/proptest-regressions/address.txt
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/lib/tests/serde.rs
  crates/lib/tests/snapshots/serde__json_mappings-2.snap
  crates/lib/tests/snapshots/serde__json_mappings.snap
  crates/sats/src/algebraic_type.rs
  crates/sats/src/hash.rs
  crates/sats/src/product_type.rs
  crates/standalone/src/control_db.rs
  crates/standalone/src/control_db/tests.rs
  smoketests/tests/identity.py
Labels: abi-break, release-1.0

#1815 Rust modules: Revise `BTreeIndexBounds`
  crates/bindings/src/table.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  modules/rust-wasm-test/src/lib.rs
Labels: api-break, release-rc1-nice-to-have

#1886 Remove CODEOWNERS from CLI codegen
  .github/CODEOWNERS
Labels: release-any, no runtime change

#1889 CLI - Fix helptext after #1845
  crates/cli/src/config.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/server.rs
Labels: release-any

#1882 Handle JWT tokens with oidc providers
  Cargo.lock
  Cargo.toml
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/client-api/src/auth.rs
  crates/core/Cargo.toml
  crates/core/src/auth/identity.rs
  crates/core/src/auth/mod.rs
  crates/core/src/auth/token_validation.rs
  crates/lib/Cargo.toml
  crates/lib/src/identity.rs
Labels: release-rc1

#1892 Small naming fixes. Fixes database identity creation.
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/util.rs
  crates/lib/src/identity.rs
  crates/testing/src/modules.rs
  smoketests/__init__.py
  smoketests/tests/auto_migration.py
  smoketests/tests/describe.py
  smoketests/tests/domains.py
  smoketests/tests/new_user_flow.py
  smoketests/tests/permissions.py
  smoketests/tests/sql.py
  smoketests/tests/zz_docker.py
Labels: release-rc1

#1907 Fix the endpoint for short-lived tokens
  crates/client-api/src/auth.rs
  crates/client-api/src/routes/identity.rs
  crates/core/src/auth/token_validation.rs
Labels: release-rc1

#1913 Bump C# bindings to 1.0.0
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
Labels: backward-compatible, release-rc1

#1876 Put `ExecutionContext` inside the Tx context
  crates/bench/benches/subscription.rs
  crates/bench/src/spacetime_raw.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/estimation.rs
  crates/core/src/execution_context.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/util/slow.rs
  crates/core/src/vm.rs
  crates/sqltest/src/space.rs
Labels: release-1.0, api-break

#1878 CLI - Login flow
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/config.rs
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/delete.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/dns.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/login.rs
  crates/cli/src/subcommands/logs.rs
  crates/cli/src/subcommands/mod.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/server.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/util.rs
  crates/testing/src/sdk.rs
  smoketests/__init__.py
  smoketests/__main__.py
  smoketests/config.toml
  smoketests/tests/domains.py
  smoketests/tests/identity.py
  smoketests/tests/permissions.py
Labels: api-break, release-rc1

#1869 C# codegen making state relative to a DbConnection
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
Labels: backward-compatible, release-rc1
