Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-12, with the labels that each got.

#1929 Remove IO macros
  crates/bindings/src/io.rs
  crates/bindings/src/lib.rs
  crates/sdk/examples/quickstart-chat/main.rs
  modules/benchmarks/src/synthetic.rs
  modules/spacetimedb-quickstart/src/lib.rs
  smoketests/tests/auto_inc.py
  smoketests/tests/auto_migration.py
  smoketests/tests/connect_disconnect_from_cli.py
  smoketests/tests/describe.py
  smoketests/tests/filtering.py
  smoketests/tests/module_nested_op.py
  smoketests/tests/modules.py
  smoketests/tests/new_user_flow.py
  smoketests/tests/panic.py
  smoketests/tests/schedule_reducer.py
  smoketests/tests/zz_docker.py
Labels: breaks library compatibility, release-1.0, api-break

#2007 Fix declaration order of ScheduleAt in C#
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/sdk/tests/test-client/src/module_bindings/indexed_table_2_table.rs
  crates/sdk/tests/test-client/src/module_bindings/indexed_table_2_type.rs
  crates/sdk/tests/test-client/src/module_bindings/indexed_table_table.rs
  crates/sdk/tests/test-client/src/module_bindings/indexed_table_type.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/module_bindings/scheduled_table_table.rs
  crates/sdk/tests/test-client/src/module_bindings/scheduled_table_type.rs
  crates/sdk/tests/test-client/src/module_bindings/send_scheduled_message_reducer.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-any, bugfix

#2031 query rewriter
  Cargo.lock
  crates/core/src/sql/parser.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/expr/src/check.rs
  crates/expr/src/errors.rs
  crates/expr/src/expr.rs
  crates/expr/src/lib.rs
  crates/expr/src/statement.rs
  crates/expr/src/ty.rs
  crates/physical-plan/Cargo.toml
  crates/physical-plan/src/compile.rs
  crates/physical-plan/src/plan.rs
  crates/schema/src/schema.rs
  crates/sql-parser/src/ast/mod.rs
  crates/sql-parser/src/ast/sql.rs
  crates/sql-parser/src/ast/sub.rs
  crates/sql-parser/src/parser/mod.rs
  crates/sql-parser/src/parser/sql.rs
  crates/sql-parser/src/parser/sub.rs
Labels: release-any

#915 CLI - Remove deprecated use of the `--project-path` flag
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/publish.rs
  crates/client-api/src/routes/tracelog.rs
Labels: CLI only, release-1.0, api-break

#2067 Reduce noisy C# compilation errors
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestIndexWithEmptyColumns.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestIndexWithoutColumns.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Type#TestUnsupportedType.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Type.verified.txt
  crates/bindings-csharp/Codegen/Diag.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
Labels: enhancement, release-any

#2043 Split Iter & IterByColRange types into Tx and MutTxId versions
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx_state.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/vm.rs
  crates/vm/src/eval.rs
Labels: release-any, release-1.0
