Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-04, with the labels that each got.

#919 (1/3) Commitlog: Base implementation "sans I/O"
  Cargo.lock
  Cargo.toml
  crates/commitlog/Cargo.toml
  crates/commitlog/LICENSE
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/error.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/payload.rs
  crates/commitlog/src/repo/mem.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/tests.rs
  crates/commitlog/src/tests/bitflip.rs
  crates/commitlog/src/tests/helpers.rs
  crates/commitlog/src/tests/partial.rs
Labels: release-any, no runtime change, commit-log

#920 (2/3) Commitlog: Add I/O based on regular files
  Cargo.lock
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/error.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/fs.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/tests/io.rs
  crates/commitlog/tests/random_payload/mod.rs
Labels: release-any, no runtime change, commit-log

#921 (3/3) Commitlog: Add canonical txdata payload
  Cargo.lock
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/payload.rs
  crates/commitlog/src/payload/txdata.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/tests/bitflip.rs
  crates/commitlog/src/tests/partial.rs
  crates/commitlog/src/varchar.rs
  crates/commitlog/src/varint.rs
  crates/commitlog/tests/random_payload/mod.rs
Labels: release-any, no runtime change, commit-log

#1014 Prune deps from bindings dependency tree
  Cargo.lock
  Cargo.toml
  crates/bindings-macro/src/lib.rs
  crates/bindings/Cargo.toml
  crates/bindings/src/rt.rs
  crates/core/Cargo.toml
  crates/lib/Cargo.toml
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/sats/Cargo.toml
  crates/sats/src/hash.rs
  crates/sdk/Cargo.toml
  modules/rust-wasm-test/Cargo.toml
  modules/rust-wasm-test/src/lib.rs
Labels: release-any

#1031 Bump to reqwest 0.12 (uses hyper 1.0)
  Cargo.lock
  Cargo.toml
Labels: release-any

#1018 Implement 'sql' parsing for simple 'Enums'
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/sats/src/algebraic_value.rs
  crates/sats/src/sum_type.rs
  crates/vm/src/ops/parse.rs
Labels: release-any, bitcraft issue, release-alpha-nice

#916 Batch metrics with ctx
  crates/bench/benches/subscription.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/execution_context.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/primitives/src/ids.rs
Labels: release-any, performance

#1041 Consistently use `--identity` `-i` for identity args to CLI
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/sql.rs
Labels: release-0.9, bitcraft issue, CLI only, api-break

#1036 Detect unsatisfiable range queries; warn and short-circuit.
  Cargo.lock
  crates/core/src/sql/execute.rs
  crates/core/src/vm.rs
  crates/vm/Cargo.toml
  crates/vm/src/expr.rs
  crates/vm/src/rel_ops.rs
Labels: bug, release-any, release-0.9, bitcraft issue

#1045 Metrics were not measuring the time it took to commit the tx
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
Labels: release-any

#570 Move lib::{name,recovery} to client-api-messages
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/cli/src/subcommands/dns.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/util.rs
  crates/client-api-messages/Cargo.toml
  crates/client-api-messages/src/lib.rs
  crates/client-api-messages/src/name.rs
  crates/client-api-messages/src/name/tests.rs
  crates/client-api-messages/src/recovery.rs
  crates/client-api/Cargo.toml
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/util.rs
  crates/lib/Cargo.toml
  crates/lib/src/lib.rs
  crates/lib/src/util.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/control_db.rs
  crates/standalone/src/lib.rs
  crates/standalone/src/main.rs
Labels: release-any, breaks library compatibility

#977 core: Make `init_module_host` consistent with `update_module_host`
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/standalone/src/lib.rs
Labels: release-any, breaks library compatibility

#922 Durability: Traits and implementation in terms of commitlog
  Cargo.lock
  Cargo.toml
  crates/commitlog/src/lib.rs
  crates/commitlog/src/payload.rs
  crates/durability/Cargo.toml
  crates/durability/LICENSE
  crates/durability/src/imp/local.rs
  crates/durability/src/imp/mod.rs
  crates/durability/src/lib.rs
Labels: release-any, no runtime change, commit-log

#786 Implement 'sql' parsing for 'Identity, Address' in hex format
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/vm/src/ops/parse.rs
Labels: release-any, bitcraft issue

#950 core: More compact TxData
  crates/bench/benches/subscription.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
Labels: release-any, commit-log

#1025 Fix iai-callgrind rustc version mismatch
  .github/workflows/benchmarks.yml
  rust-toolchain.toml
Labels: release-any

#1052 Slow query log
  crates/bench/benches/subscription.rs
  crates/core/src/config.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/execution_context.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/util/mod.rs
  crates/core/src/util/slow.rs
  crates/core/src/vm.rs
  crates/sqltest/src/space.rs
  crates/vm/src/errors.rs
  crates/vm/src/expr.rs
  crates/vm/src/program.rs
Labels: release-any, release-alpha-nice

#1130 Use -s to specify server for spacetime identity list -s <server>
  crates/cli/src/subcommands/identity.rs
Labels: release-any, CLI only, api-break

#1131 Fix an inconsistency with spacetime server fingerprint
  crates/cli/src/subcommands/server.rs
Labels: release-any, CLI only, api-break

#1150 Tests use explicit `--server local`
  crates/testing/src/sdk.rs
Labels: release-any, no runtime change

#1078 CLI - Set default server to `testnet`
  crates/cli/src/config.rs
Labels: release-any, CLI only

#1102 Dylan/doc: Link directly to cargo install on missing
  crates/cli/src/subcommands/init.rs
Labels: documentation

#1143 Simplify C# source generator csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Codegen/tools/install.ps1
  crates/bindings-csharp/Codegen/tools/uninstall.ps1
  smoketests/__init__.py
  smoketests/tests/csharp_module.py
Labels: release-any

#1114 Disallow calling random lifecycle reducers
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/lib/src/lib.rs
  smoketests/tests/permissions.py
Labels: release-any

#1171 chore: Remove unused server metrics
  crates/core/src/db/db_metrics/mod.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/worker_metrics/mod.rs
Labels: release-any

#1172 fix(1170): Use scope guard to decrement reducer queue length
  crates/core/src/host/module_host.rs
  crates/core/src/util/lending_pool.rs
  crates/core/src/worker_metrics/mod.rs
Labels: release-any

#1174 fix(1173): Record wait time for all reducers
  crates/core/src/host/module_host.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/worker_metrics/mod.rs
  crates/standalone/src/lib.rs
Labels: release-any
