Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-05, with the labels that each got.

#1180 Add PR status check that fails unless based on `master`
  .github/workflows/check-pr-base.yml
Labels: release-any, no runtime change

#1191 C#: rename DbEventArgs to ReducerContext
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-cs/Lib.cs
Labels: api-break

#1205 Bump to Rust 1.78
  .github/workflows/benchmarks.yml
  Cargo.toml
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/util/notify_once.rs
  crates/data-structures/src/slim_slice.rs
  crates/sdk/tests/test-client/src/pk_test_table.rs
  crates/sdk/tests/test-client/src/simple_test_table.rs
  crates/sdk/tests/test-client/src/unique_test_table.rs
  crates/standalone/Dockerfile
  crates/table/benches/page_manager.rs
  crates/testing/src/sdk.rs
  rust-toolchain.toml
Labels: breaks library compatibility

#1190 Remove RowUpdate event from C#
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_output.snap
Labels: api-break

#1177 Switch to a better API for tagged enums for C#
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Codegen/README.md
  crates/bindings-csharp/Codegen/Type.cs
  crates/bindings-csharp/Codegen/Utils.cs
  crates/bindings-csharp/Runtime/AlgebraicType.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Filter.cs
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  modules/sdk-test-cs/Lib.cs
Labels: api-break, release-0.10

#1075 Drop various logs to `trace` for less noise
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/segment.rs
  crates/durability/src/imp/local.rs
Labels: release-alpha, backward-compatible

#1213 Fix #1180: Add PR status check that fails unless based on master
  .github/workflows/check-pr-base.yml
Labels: release-any

#1196 Create a lockfile when opening config files
  crates/cli/src/config.rs
  crates/cli/src/lib.rs
  crates/cli/src/main.rs
  crates/cli/src/subcommands/build.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/init.rs
  crates/cli/src/subcommands/local.rs
  crates/cli/src/subcommands/upgrade.rs
  crates/cli/src/subcommands/version.rs
  crates/testing/src/lib.rs
Labels: release-any, CLI only

#1055 Bump version to 0.9.0
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-0.9, backward-compatible

#1221 Add CODEOWNERS for `rust-toolchain.toml`
  .github/CODEOWNERS
Labels: release-any, no runtime change

#1218 Fix select * from *
  crates/bench/benches/subscription.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/query.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test.rs
Labels: release-any

#1169 CLI - Small refactors to identity code
  crates/cli/src/config.rs
  crates/cli/src/subcommands/identity.rs
Labels: release-any, CLI only

#1225 Add CODEOWNERS for `LICENSE.txt`
  .github/CODEOWNERS
Labels: release-any, no runtime change

#1226 Add `CODEOWNERS` for `CODEOWNERS`
  .github/CODEOWNERS
Labels: release-any, no runtime change

#1038 `spacetime publish`: Add confirmation for `-c`
  crates/cli/src/subcommands/publish.rs
  smoketests/__init__.py
  smoketests/tests/permissions.py
Labels: release-any, bitcraft issue

#1140 Make identity naming more consistent + fix bugs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/util.rs
Labels: release-any, CLI only

#1111 Always send TransactionUpdate to the sender
  crates/core/src/client/client_connection.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/module_bindings/no_op_succeeds_reducer.rs
  crates/sdk/tests/test.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-any

#1186 core: Collapse DBIC into HostController
  Cargo.lock
  Cargo.toml
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/database_instance_context.rs
  crates/core/src/database_instance_context_controller.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/module_host.rs
  crates/core/src/lib.rs
  crates/core/src/module_host_context.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/control_db.rs
  crates/standalone/src/lib.rs
  crates/testing/src/modules.rs
Labels: release-any

#1265 Reserve sequence range for system tables
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/vm.rs
Labels: abi-break

#1147 Module hotswapping
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/database_instance_context.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/util/future_queue.rs
  crates/core/src/util/mod.rs
  crates/testing/src/modules.rs
Labels: release-any, test-with-bots

#1280 Consistent filtering rules for Rust bindings
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/impls.rs
Labels: api-break

#1002 recv-style abi
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/RawBindings.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/bindings.c
  crates/bindings-sys/src/errno.rs
  crates/bindings-sys/src/lib.rs
  crates/bindings/src/lib.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/lib/src/lib.rs
  crates/primitives/src/errno.rs
  crates/primitives/src/lib.rs
  crates/sats/src/buffer.rs
Labels: abi-break, test-with-bots, release-1.0

#1132 Disconnect dangling clients
  crates/core/src/database_instance_context.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common.rs
Labels: release-any

#1289 CI workflows support `workflow_dispatch` event
  .github/workflows/ci.yml
Labels: release-any, no runtime change

#1298 fix(1297): `spacetime logs -f` should not start at the very beginning
  crates/cli/src/subcommands/logs.rs
Labels: release-any, CLI only

#1302 CLI - Fix `Lockfile` error message format strings
  crates/cli/src/config.rs
Labels: release-any, CLI only

#1303 CLI - Drop Config lock earlier for `spacetime logs`
  crates/cli/src/subcommands/logs.rs
Labels: release-any, CLI only

#985 Commitlog: panic on fsync failure
  Cargo.lock
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/error.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/tests/partial.rs
  crates/durability/src/imp/local.rs
Labels: release-any

#1224 Bump version to 0.9.3
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any

#1293 feat(1231): Add a configurable row limit for queries
  crates/core/src/config.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/estimation.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
Labels: release-any

#1309 Fix FilterBy regression in C#
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
Labels: release-any, bugfix

#1311 Bump ABI version for C# AOT
  crates/bindings-csharp/Runtime/RawBindings.cs
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.props
Labels: release-any, bugfix

#1283 Implement new rand api
  Cargo.lock
  Cargo.toml
  crates/bindings-sys/Cargo.toml
  crates/bindings-sys/src/lib.rs
  crates/bindings/Cargo.toml
  crates/bindings/src/lib.rs
  crates/bindings/src/rng.rs
  crates/bindings/src/rt.rs
  crates/cli/src/tasks/rust.rs
  modules/spacetimedb-quickstart/Cargo.toml
  smoketests/tests/detect_wasm_bindgen.py
Labels: api-break, release-0.10

#1255 Automated bot tests
  .github/workflows/bottest.yml
  .github/workflows/bottest_tracing_fix.patch
Labels: release-any, no runtime change
