Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-02, with the labels that each got.

#764 1_000_000 insert + update benchmarks
  crates/bench/README.md
  crates/bench/benches/callgrind.rs
  crates/bench/benches/generic.rs
  crates/bench/callgrind-docker.sh
  crates/bench/src/database.rs
  crates/bench/src/lib.rs
  crates/bench/src/schemas.rs
  crates/bench/src/spacetime_module.rs
  crates/bench/src/spacetime_raw.rs
  crates/bench/src/sqlite.rs
  modules/benchmarks/src/lib.rs
Labels: after memarch

#732 Move legacy control_db from core to standalone
  Cargo.lock
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/lib.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/control_db.rs
  crates/standalone/src/control_db/tests.rs
  crates/standalone/src/energy_monitor.rs
  crates/standalone/src/lib.rs
Labels: release-any, verify labels

#811 Bump Rust to 1.76.0
  .github/workflows/ci.yml
  Cargo.toml
  crates/bench/Dockerfile
  crates/bench/src/bin/summarize.rs
  crates/bindings/src/rt.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/core/src/db/messages/transaction.rs
  crates/sats/src/algebraic_value/ser.rs
  crates/sdk/src/websocket.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sqltest/src/space.rs
  crates/standalone/Dockerfile
  rust-toolchain.toml
  test/lib.include
Labels: breaks library compatibility

#795 test: Add performance benchmark for incremental join query
  Cargo.toml
  crates/bench/Cargo.toml
  crates/bench/benches/subscription.rs
  crates/core/src/host/mod.rs
Labels: no runtime change

#812 chore(datastore): Remove debug instrumentation
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
Labels: release-any, no runtime change

#806 This fixes replaying of the transaction log to no longer check constraints
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/table/src/table.rs
Labels: release-any, bugfix, release-0.8.2-hotfix

#804 `ScanIterByColRange`: Avoid unnecessary `ProductValue` allocations
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
Labels: release-any, performance

#807 To make eval subscription concurrent
  crates/core/src/client/client_connection.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/subscription/module_subscription_actor.rs
Labels: release-any, performance

#841 Remove unused pre-publish.duck file
  crates/cli/src/subcommands/project/rust/pre-publish.duck
Labels: release-any

#814 Fix: Publish fails if rustup not present
  crates/cli/src/tasks/rust.rs
Labels: CLI only

#756 Add workflow to tag latest docker image on release
  .github/workflows/tag-release.yml
Labels: no runtime change

#810 Reduce allocations for prometheus with_label_values
  Cargo.lock
  crates/core/src/execution_context.rs
  crates/core/src/host/mod.rs
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/metrics/Cargo.toml
  crates/metrics/src/typed_prometheus.rs
  crates/sats/src/hash.rs
Labels: release-any, performance

#853 Fix publish issues 0.8.2
  crates/lib/Cargo.toml
  crates/table/Cargo.toml
  crates/table/LICENSE
Labels: release-any

#857 Fix identity subcommand ordering
  crates/cli/src/subcommands/identity.rs
Labels: release-any, CLI only

#734 core: Ignore `indexed`-only constraints when updating
  crates/core/src/db/update.rs
Labels: release-any, bugfix, release-0.8.2-hotfix

#751 Use a version label for tag builds
  tools/merge-docker-images.sh
Labels: release-any, no runtime change

#854 Fix deadlock
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/module_host.rs
  crates/core/src/subscription/module_subscription_actor.rs
Labels: release-any, bugfix

#855 Fix bench errors and include in CI
  .github/workflows/ci.yml
  crates/table/benches/page.rs
  crates/table/benches/page_manager.rs
  crates/table/benches/var_len_visitor.rs
Labels: release-any, no runtime change

#852 chore: Remove instrumentation from DataKey deserializers
  crates/core/src/db/relational_db.rs
  crates/sats/src/bsatn.rs
  crates/sats/src/hash.rs
Labels: release-any, performance

#862 Add GitHub workflow to check for PRs with merge-blocking labels
  .github/workflows/check-merge-labels.yml
Labels: release-any, no runtime change

#803 Rename types in benchmarks
  .github/workflows/benchmarks.yml
  crates/bench/benches/callgrind.rs
  crates/bench/benches/generic.rs
  crates/bench/benches/special.rs
  crates/bench/src/database.rs
  crates/bench/src/lib.rs
  crates/bench/src/schemas.rs
  crates/bench/src/spacetime_module.rs
  crates/bench/src/spacetime_raw.rs
  crates/bench/src/sqlite.rs
  modules/benchmarks/src/lib.rs
Labels: release-any, no runtime change

#704 C#: reuse Consume helper
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/Runtime.cs
Labels: release-any, no runtime change

#863 perf(832): Remove redundant row deduplication in subscriptions
  crates/bench/benches/subscription.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
Labels: release-any, performance
