Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-08, with the labels that each got.

#1562 Minor NFC improvements to C# Roslyn codegen
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen.Tests/Codegen.Tests.csproj
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#CustomTaggedEnum.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Directory.Build.props
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/Runtime.csproj
Labels: release-any

#1549 `Typespace::is_nominal_normal_form`
  crates/sats/proptest-regressions/typespace.txt
  crates/sats/src/algebraic_type.rs
  crates/sats/src/product_type.rs
  crates/sats/src/proptest.rs
  crates/sats/src/sum_type.rs
  crates/sats/src/typespace.rs
Labels: release-any

#1542 Add lib::db::{column_ordering, raw_def::v9}
  crates/lib/Cargo.toml
  crates/lib/proptest-regressions/db/column_ordering.txt
  crates/lib/src/db/default_element_ordering.rs
  crates/lib/src/db/mod.rs
  crates/lib/src/db/raw_def.rs
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/lib.rs
  crates/sats/Cargo.toml
  crates/sats/src/typespace.rs
  crates/schema/Cargo.toml
Labels: enhancement, release-any

#1565 Change ResolveRefs to return a Result rather than an Option
  crates/bindings/src/rt.rs
  crates/client-api/src/routes/database.rs
  crates/sats/src/resolve_refs.rs
Labels: api-break, release-0.12

#1558 core: Use `Program` instead of `(Hash, Box<[u8]>)`
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/core/src/module_host_context.rs
  crates/core/src/util/mod.rs
Labels: release-any

#1582 Fix [iu](128|256) BSATN implementations in C#
  crates/bindings-csharp/BSATN.Runtime/BSATN/I128.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/I256.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/U128.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/U256.cs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_primitives_as_strings_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-any, bugfix

#1570 C#: disable verbose test output in console
  crates/bindings-csharp/Codegen.Tests/TestInit.cs
Labels: release-any, no runtime change

#1576 Verify Unity compatibility in the shared C# codegen
  crates/bindings-csharp/Codegen.Tests/Codegen.Tests.csproj
  crates/bindings-csharp/Codegen.Tests/TestInit.cs
  crates/bindings-csharp/Codegen.Tests/Tests.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/client.csproj
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomTaggedEnum.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/server.csproj
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomTaggedEnum.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#Timers.SendMessageTimer.verified.cs
Labels: release-any, no runtime change

#1590 Make `ScheduleAt` special + `Typespace::is_valid_for_client_code_generation`
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  crates/core/src/sql/compiler.rs
  crates/lib/src/address.rs
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/identity.rs
  crates/lib/src/scheduler.rs
  crates/lib/tests/serde.rs
  crates/sats/src/algebraic_type.rs
  crates/sats/src/product_type.rs
  crates/sats/src/proptest.rs
  crates/sats/src/resolve_refs.rs
  crates/sats/src/sum_type.rs
  crates/sats/src/typespace.rs
  modules/rust-wasm-test/src/lib.rs
Labels: release-any, abi-break, api-break

#1587 Dedup schedueler queue
  crates/core/src/host/scheduler.rs
Labels: backward-compatible, release-0.12

#1626 Updated docker internal port to 3000
  crates/standalone/src/subcommands/start.rs
  docker-compose.yml
Labels: api-break

#1632 smoketests: Test unauthorized publish without -c
  smoketests/tests/permissions.py
Labels: release-any

#1572 ABI v9 validation code
  Cargo.lock
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/sats/src/product_type.rs
  crates/schema/Cargo.toml
  crates/schema/src/def.rs
  crates/schema/src/def/validate.rs
  crates/schema/src/def/validate/v8.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
  crates/schema/src/lib.rs
Labels: release-any

#1606 Add backwards-compatible validation for RawModuleDefV8.
  Cargo.lock
  crates/data-structures/src/error_stream.rs
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/lib.rs
  crates/schema/Cargo.toml
  crates/schema/src/def.rs
  crates/schema/src/def/validate.rs
  crates/schema/src/def/validate/v8.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
  crates/schema/tests/validate_integration.rs
Labels: release-any

#1623 Update SQL AST in accordance with the SQL spec
  Cargo.lock
  Cargo.toml
  crates/sql-parser/Cargo.toml
  crates/sql-parser/src/ast/mod.rs
  crates/sql-parser/src/ast/sql.rs
  crates/sql-parser/src/ast/sub.rs
  crates/sql-parser/src/lib.rs
  crates/sql-parser/src/parser/errors.rs
  crates/sql-parser/src/parser/mod.rs
  crates/sql-parser/src/parser/sql.rs
  crates/sql-parser/src/parser/sub.rs
Labels: enhancement, release-1.0
