Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-11, with the labels that each got.

#1851 commitlog: Introduce epoch
  crates/commitlog/proptest-regressions/tests/bitflip.txt
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/payload/txdata.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
Labels: backward-compatible, release-rc1-nice-to-have

#1922 Fix benches for ia_loop, circles
  crates/bench/benches/special.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/benchmarks/src/ia_loop.rs
Labels: release-any, bugfix, release-1.0

#1910 Logical to physical plan lowering
  crates/core/src/sql/ast.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/expr/src/check.rs
  crates/expr/src/expr.rs
  crates/expr/src/lib.rs
  crates/expr/src/statement.rs
  crates/physical-plan/src/compile.rs
  crates/physical-plan/src/lib.rs
  crates/physical-plan/src/plan.rs
Labels: release-1.0, backward-compatible

#1926 Be more careful about endianness with Identity and Address
  crates/bindings/src/rt.rs
  crates/client-api/src/routes/identity.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/lib/proptest-regressions/identity.txt
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/standalone/src/control_db.rs
Labels: abi-break, release-rc1

#1956 Removing dead code: Relational ops and cursor
  crates/core/src/db/cursor.rs
  crates/core/src/db/mod.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/relational_operators.rs
Labels: release-any, release-1.0

#1962 Bump version to 1.0.0-rc2
  Cargo.lock
  Cargo.toml
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any, no runtime change

#1969 CLI - Remove unused `default_identity` stuff
  crates/cli/src/config.rs
Labels: release-any, CLI only

#1955 CLI - Tell users if they're already logged in
  crates/cli/src/subcommands/login.rs
Labels: release-any, CLI only

#1954 CLI - Fix stale helptext instructing users to use `spacetime identity`
  crates/cli/src/util.rs
Labels: release-any, CLI only

#1879 Directory structure impl
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/bench/src/spacetime_module.rs
  crates/cli/Cargo.toml
  crates/cli/src/config.rs
  crates/cli/src/lib.rs
  crates/cli/src/main.rs
  crates/cli/src/subcommands/server.rs
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/database.rs
  crates/commitlog/Cargo.toml
  crates/commitlog/src/index/indexfile.rs
  crates/commitlog/src/index/mod.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/fs.rs
  crates/commitlog/tests/random_payload/mod.rs
  crates/core/Cargo.toml
  crates/core/src/auth/mod.rs
  crates/core/src/config.rs
  crates/core/src/database_logger.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/core/src/lib.rs
  crates/core/src/replica_context.rs
  crates/core/src/startup.rs
  crates/durability/Cargo.toml
  crates/durability/src/imp/local.rs
  crates/fs-utils/src/lib.rs
  crates/fs-utils/src/lockfile.rs
  crates/paths/Cargo.toml
  crates/paths/LICENSE
  crates/paths/src/cli.rs
  crates/paths/src/lib.rs
  crates/paths/src/server.rs
  crates/paths/src/standalone.rs
  crates/paths/src/utils.rs
  crates/snapshot/Cargo.toml
  crates/snapshot/src/lib.rs
  crates/standalone/Cargo.toml
  crates/standalone/Dockerfile
  crates/standalone/config.toml
  crates/standalone/log.conf
  crates/standalone/src/control_db.rs
  crates/standalone/src/lib.rs
  crates/standalone/src/subcommands/start.rs
  crates/standalone/src/util.rs
  crates/testing/Cargo.toml
  crates/testing/src/lib.rs
  crates/testing/src/modules.rs
  crates/testing/src/sdk.rs
  docker-compose.yml
  smoketests/__init__.py
Labels: abi-break, release-rc1-nice-to-have

#1895 Optimize integrate_generated_columns
  crates/bindings-macro/src/table.rs
  crates/bindings/src/table.rs
  crates/commitlog/src/payload.rs
  crates/sats/src/buffer.rs
  crates/standalone/src/control_db.rs
Labels: release-any

#1990 Update run_standalone_temp.sh to the new folder specification
  run_standalone_temp.sh
Labels: release-any, release-1.0

#1864 Durability Provider
  Cargo.lock
  crates/client-api/Cargo.toml
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/standalone/src/lib.rs
  crates/testing/src/modules.rs
Labels: release-any, backward-compatible

#1964 C# endianness fixes
  crates/bindings-csharp/BSATN.Runtime.Tests/BSATN.Runtime.Tests.csproj
  crates/bindings-csharp/BSATN.Runtime.Tests/Tests.cs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/bindings-csharp/SpacetimeSharpSATS.sln
Labels: bugfix, release-rc1

#1918 Rip useless names out of RawDef
  Cargo.lock
  crates/bench/benches/subscription.rs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#BTreeMultiColumn.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#BTreeViews.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#MultiTableRow.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScheduleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV9.cs
  crates/bindings-csharp/Runtime/README.md
  crates/bindings-macro/src/table.rs
  crates/bindings-sys/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/src/table.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/estimation.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/schema/Cargo.toml
  crates/schema/src/auto_migrate.rs
  crates/schema/src/def.rs
  crates/schema/src/def/validate/v8.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
  crates/schema/src/type_for_generate.rs
  crates/schema/tests/validate_integration.rs
  crates/table/benches/page_manager.rs
  crates/table/src/table.rs
Labels: abi-break, release-1.0

#1894 Don't autogen schedule fields
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/table.rs
  crates/bindings-macro/src/util.rs
  crates/bindings/src/table.rs
  crates/bindings/tests/ui/reducers.rs
  crates/bindings/tests/ui/reducers.stderr
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  modules/rust-wasm-test/src/lib.rs
  smoketests/tests/modules.py
  smoketests/tests/schedule_reducer.py
Labels: release-rc1-nice-to-have

#1996 CLI should not depend on rustup
  crates/cli/src/detect.rs
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/init.rs
  crates/cli/src/tasks/rust.rs
Labels: CLI only, release-1.0
