Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-09, with the labels that each got.

#1663 Add edition to .rustfmt.toml
  .rustfmt.toml
Labels: release-any, no runtime change

#1573 C#: split table codegen logic from type codegen logic
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#CustomTaggedEnum.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomTaggedEnum.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
Labels: release-any

#1680 Auto-generate C# ModuleDef bindings from Rust
  .gitattributes
  Cargo.lock
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/Codegen.Tests/TestInit.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/IndexType.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/Lifecycle.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/MiscModuleExport.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawColumnDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexAlgorithm.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawMiscModuleExportV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDef.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawReducerDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScheduleDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScopedTypeNameV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV8.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTypeDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawUniqueConstraintDefV9.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/ReducerDef.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableAccess.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableDesc.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableType.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TypeAlias.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/Typespace.cs
  crates/bindings-csharp/Runtime/Internal/IReducer.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/cli/Cargo.toml
  crates/cli/examples/regen-csharp-moduledef.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/lib/src/db/auth.rs
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/lib.rs
  crates/lib/src/scheduler.rs
  crates/sats/src/algebraic_type.rs
  crates/sats/src/algebraic_type_ref.rs
  crates/sats/src/array_type.rs
  crates/sats/src/map_type.rs
  crates/sats/src/primitives.rs
  crates/sats/src/product_type.rs
  crates/sats/src/product_type_element.rs
  crates/sats/src/ser/impls.rs
  crates/sats/src/sum_type.rs
  crates/sats/src/sum_type_variant.rs
  crates/sats/src/typespace.rs
Labels: release-any

#1314 Impl macro rework
  Cargo.lock
  Cargo.toml
  crates/bindings-macro/Cargo.toml
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/macros.rs
  crates/bindings-macro/src/module.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/src/subcommands/project/rust/lib._rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/update.rs
  crates/sdk/src/callbacks.rs
  crates/sdk/src/table.rs
  modules/benchmarks/src/circles.rs
  modules/benchmarks/src/ia_loop.rs
  modules/benchmarks/src/synthetic.rs
  modules/perf-test/src/lib.rs
  modules/quickstart-chat/src/lib.rs
  modules/rust-wasm-test/src/lib.rs
  modules/sdk-test-connect-disconnect/src/lib.rs
  modules/sdk-test/src/lib.rs
  modules/spacetimedb-quickstart/src/lib.rs
  smoketests/tests/add_remove_index.py
  smoketests/tests/add_table_pseudomigration.py
  smoketests/tests/auto_inc.py
  smoketests/tests/connect_disconnect_from_cli.py
  smoketests/tests/describe.py
  smoketests/tests/detect_wasm_bindgen.py
  smoketests/tests/filtering.py
  smoketests/tests/module_nested_op.py
  smoketests/tests/modules.py
  smoketests/tests/new_user_flow.py
  smoketests/tests/panic.py
  smoketests/tests/permissions.py
  smoketests/tests/schedule_reducer.py
  smoketests/tests/sql.py
  smoketests/tests/zz_docker.py
  test/tests/update-module.sh
Labels: Do not merge, api-break, release-0.12

#1658 Automatic migration planning
  crates/schema/src/auto_migrate.rs
  crates/schema/src/def.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/lib.rs
Labels: release-any

#1699 WASM ABI: add `datastore_btree_scan_bsatn` & `index_id_from_name`
  Cargo.lock
  Cargo.toml
  crates/bindings-sys/src/lib.rs
  crates/core/Cargo.toml
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx_state.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/error.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/primitives/src/errno.rs
  crates/sats/src/algebraic_value.rs
  crates/sats/src/algebraic_value/ser.rs
  crates/sats/src/algebraic_value_hash.rs
  crates/sats/src/bsatn.rs
  crates/sats/src/bsatn/eq.rs
  crates/sats/src/buffer.rs
  crates/sats/src/de.rs
  crates/sats/src/de/impls.rs
  crates/sats/src/lib.rs
  crates/sats/src/product_type.rs
  crates/sats/src/ser/impls.rs
  crates/table/src/btree_index.rs
  crates/table/src/table.rs
Labels: release-any

#1687 NFC: enforce more C# code style + enable it in Visual Studio
  crates/bindings-csharp/.editorconfig
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Runtime/Attrs.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/bindings-csharp/BSATN.Runtime/Internal/ByteArrayComparer.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Directory.Build.props
  crates/bindings-csharp/SpacetimeSharpSATS.sln
Labels: release-any

#1709 snapshot: pub access to snapshot file + object repo
  crates/snapshot/src/lib.rs
Labels: release-any

#1675 Switch Rust codegen to use new ModuleDef
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-macro/src/lib.rs
  crates/cli/examples/regen-csharp-moduledef.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/client-api-messages/examples/get_ws_schema.rs
  crates/lib/src/lib.rs
  crates/schema/src/def/validate/v8.rs
  crates/schema/src/type_for_generate.rs
  crates/schema/tests/validate_integration.rs
Labels: release-any

#1681 Stopwatch and reducer rng
  .gitignore
  crates/bindings-csharp/Runtime/Exceptions.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/LogStopwatch.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/bindings.c
  crates/bindings/src/lib.rs
  crates/bindings/src/log_stopwatch.rs
  crates/primitives/src/errno.rs
  modules/perf-test/src/lib.rs
Labels: api-break, release-0.12

#1720 Fixes showing server errors on `cli sql` calls
  crates/cli/src/errors.rs
Labels: CLI only, release-1.0

#1715 CI - Discord post will ping a particular role if CI check was not successful
  .github/workflows/discord-posts.yml
Labels: no runtime change

#1673 CLI - Print out config path when saving
  crates/cli/src/config.rs
Labels: release-any, CLI only

#1667 CLI - Fix helptext for `spacetime sql`
  crates/cli/src/subcommands/sql.rs
Labels: release-any, CLI only

#1693 CLI - Remove unused `tracelog.rs`
  crates/cli/src/subcommands/tracelog.rs
Labels: release-any, CLI only

#1714 Logging API
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/Log.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/cli/src/subcommands/project/csharp/Lib._cs
  modules/benchmarks-cs/circles.cs
  modules/benchmarks-cs/ia_loop.cs
  modules/benchmarks-cs/synthetic.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
Labels: api-break

#1671 Commitlog offset index
  Cargo.lock
  crates/bindings/tests/snapshots/deps__duplicate_deps.snap
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/index/indexfile.rs
  crates/commitlog/src/index/mod.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/fs.rs
  crates/commitlog/src/repo/mem.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/tests/partial.rs
  tools/upgrade-version/src/main.rs
Labels: release-1.0, backward-compatible

#1665 CLI - Remove project-specific config files
  crates/cli/src/config.rs
Labels: CLI only, api-break, release-0.12

#1669 CLI - Exit when config is malformed
  crates/cli/src/config.rs
  crates/cli/src/main.rs
Labels: release-any, CLI only

#1697 Update TableSchema & system tables to resemble ABI V9
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/benches/special.rs
  crates/bench/src/spacetime_module.rs
  crates/bench/src/spacetime_raw.rs
  crates/cli/src/api.rs
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/database.rs
  crates/core/src/client/message_handlers.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/error.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/sql/type_check.rs
  crates/core/src/vm.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/lib.rs
  crates/lib/src/relation.rs
  crates/planner/src/logical/bind.rs
  crates/primitives/src/attr.rs
  crates/primitives/src/col_list.rs
  crates/primitives/src/ids.rs
  crates/primitives/src/lib.rs
  crates/sats/src/convert.rs
  crates/sats/src/de/impls.rs
  crates/sats/src/ser/impls.rs
  crates/sats/src/typespace.rs
  crates/schema/Cargo.toml
  crates/schema/src/auto_migrate.rs
  crates/schema/src/def.rs
  crates/schema/src/def/deserialize.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
  crates/schema/src/schema.rs
  crates/schema/tests/validate_integration.rs
  crates/sdk/tests/test-client/src/module_bindings/simple_enum.rs
  crates/standalone/src/lib.rs
  crates/table/Cargo.toml
  crates/table/benches/page_manager.rs
  crates/table/src/btree_index.rs
  crates/table/src/read_column.rs
  crates/table/src/table.rs
  crates/vm/src/expr.rs
Labels: abi-break, release-0.12

#1719 Jeremie/cs module
  crates/bindings-csharp/BSATN.Runtime/Db.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Internal/IReducer.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/LogStopwatch.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/SpacetimeSharpSATS.sln
  crates/cli/src/subcommands/project/csharp/Lib._cs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-connect-disconnect-cs/sdk-test-connect-disconnect-cs.csproj
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test-cs/sdk-test-cs.csproj
  modules/sdk-test-multi-cs/.gitignore
  modules/sdk-test-multi-cs/Lib.cs
  modules/sdk-test-multi-cs/README.md
  modules/sdk-test-multi-cs/sdk-test-multi-cs.csproj
  modules/spacetimedb-quickstart-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/spacetimedb-quickstart-server-cs.csproj
Labels: abi-break

#1745 CLI - Change default server back to `local`
  crates/cli/src/config.rs
Labels: CLI only, release-0.12

#1742 CLI - `publish` and `generate` take a `--build-options` param
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/build.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/publish.rs
  crates/testing/src/sdk.rs
Labels: CLI only, release-0.12

#1759 CLI - `local clear` -> `server clear`
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/local.rs
  crates/cli/src/subcommands/mod.rs
  crates/cli/src/subcommands/server.rs
Labels: CLI only, api-break, release-0.12

#1751 CLI - `--anon-identity` -> `--anonymous`
  crates/cli/src/common_args.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
  smoketests/__init__.py
Labels: CLI only, release-0.12

#1752 CLI - `--force` -> `--yes`/`-y`
  crates/cli/src/common_args.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/server.rs
  crates/cli/src/util.rs
  smoketests/__init__.py
  smoketests/tests/identity.py
  smoketests/tests/permissions.py
  smoketests/tests/servers.py
Labels: CLI only, release-0.12

#1755 Remove the `expand` option on the `describe` route
  crates/cli/src/subcommands/describe.rs
  crates/client-api/src/routes/database.rs
Labels: api-break, release-0.12

#1754 refactor: Intern names in relation expressions
  Cargo.lock
  Cargo.toml
  crates/planner/Cargo.toml
  crates/planner/src/logical/bind.rs
  crates/planner/src/logical/errors.rs
  crates/planner/src/logical/expr.rs
  crates/planner/src/logical/mod.rs
  crates/planner/src/logical/stmt.rs
  crates/planner/src/logical/ty.rs
  crates/sql-parser/src/ast/mod.rs
  crates/sql-parser/src/ast/sql.rs
  crates/sql-parser/src/parser/errors.rs
  crates/sql-parser/src/parser/mod.rs
  crates/sql-parser/src/parser/sql.rs
Labels: release-0.12

#1741 CLI stabilization
  crates/cli/src/subcommands/build.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/logs.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/subcommands/version.rs
  crates/client-api-messages/DEVELOP.md
  crates/testing/src/sdk.rs
  smoketests/__init__.py
  smoketests/tests/permissions.py
Labels: CLI only, api-break, release-0.12

#1772 [C#] Remove .Query support
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestAutoIncNotInteger.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestUniqueNotEquatable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#MultiTableRow.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/Filter.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
Labels: api-break

#1756 feat: Integrate type checking into current query code
  Cargo.lock
  Cargo.toml
  crates/bench/benches/subscription.rs
  crates/core/Cargo.toml
  crates/core/src/error.rs
  crates/core/src/estimation.rs
  crates/core/src/host/module_host.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/util/slow.rs
  crates/sqltest/src/space.rs
Labels: release-0.12

#1769 [C#] Mark experimental API
  crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#MultiTableRow.InsertMultiData.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Reducers.InsertData.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Reducers.ScheduleImmediate.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Test.NestingNamespaces.AndClasses.InsertData2.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.Init.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendScheduledMessage.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
Labels: api-break
