Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-03, with the labels that each got.

#910 Correctly show the error for AmbiguousField and simplify the code
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
Labels: bug, release-any, no runtime change

#694 Adding an index selector that take in account multi-column indexes (and improve the `query!` macro)
  Cargo.lock
  Cargo.toml
  crates/bench/benches/subscription.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/sats/src/relation.rs
  crates/vm/Cargo.toml
  crates/vm/src/expr.rs
Labels: release-0.9

#900 Fix the RowCount estimation for select operator
  crates/vm/src/rel_ops.rs
Labels: release-any, performance

#930 Kick clients that are backing up their message channel
  Cargo.lock
  Cargo.toml
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/client.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/subcommands/start.rs
Labels: include-in-perf-test

#946 Truly remove perfcnt
  Cargo.lock
  Cargo.toml
  crates/table/Cargo.toml
Labels: release-any

#967 Fix bench for location, restore single-column indexes
  crates/bench/benches/subscription.rs
  crates/core/src/db/relational_db.rs
Labels: release-any, no runtime change

#883 spacetime publish: Add `--wasm-file` flag
  crates/cli/src/subcommands/build.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/publish.rs
Labels: release-any, CLI only

#937 Misc tweaks to `tools/perf.sh`
  tools/perf.sh
Labels: include-in-perf-test

#974 core: Fix schema checks in database updates, again
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/db/update.rs
Labels: test-with-bots

#981 perf(833): Do not clone query plan during execution
  crates/bench/src/spacetime_raw.rs
  crates/core/src/db/cursor.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/sats/src/relation.rs
  crates/vm/src/eval.rs
  crates/vm/src/expr.rs
  crates/vm/src/program.rs
  crates/vm/src/rel_ops.rs
  crates/vm/src/relation.rs
Labels: release-any, performance, include-in-perf-test

#951 perf(933): Clone bsatn instead of product values in incremental update
  crates/core/src/client/client_connection.rs
  crates/core/src/client/message_handlers.rs
  crates/core/src/client/messages.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: release-any, test-with-bots, include-in-perf-test

#939 fix: Optimize query plan in iter_filtered_chunks
  crates/core/src/db/relational_db.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/vm.rs
  crates/sqltest/src/db.rs
Labels: release-any, bugfix, test-with-bots, include-in-perf-test

#986 Don't do alignment computations during BFLATN ser/de
  crates/table/proptest-regressions/bflatn_to.txt
  crates/table/proptest-regressions/read_column.txt
  crates/table/src/bflatn_from.rs
  crates/table/src/bflatn_to.rs
  crates/table/src/read_column.rs
Labels: release-any, performance, include-in-perf-test

#987 Remove useless usages of RowCount
  crates/core/src/db/cursor.rs
  crates/core/src/vm.rs
  crates/sats/src/relation.rs
  crates/vm/src/rel_ops.rs
Labels: release-any, performance, include-in-perf-test

#990 Nuke `to_mem_table_with_op_type`
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/query.rs
Labels: release-any, performance, include-in-perf-test

#1004 Show the error text of the server when a sql call fails on cli
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/errors.rs
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/sql.rs
Labels: release-any, CLI only

#1017 Shub/remove lifetime from ctx
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/execution_context.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/vm.rs
Labels: release-any

#901 Fixed an issue which caused metrics to only be recorded for on-disk databases
  crates/core/src/db/commit_log.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/traits.rs
Labels: release-any, bugfix, release-alpha

#1026 Binary WebSocket API: Brotli-compress all outgoing messages
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/client/messages.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/websocket.rs
Labels: bitcraft issue, performance, breaks library compatibility, test-with-bots, release-alpha, websocket-compression
