Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-06, with the labels that each got.

#1330 Fix commitlog `fold_transactions_from` ignoring requested offset
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/payload.rs
  crates/commitlog/src/payload/txdata.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
Labels: bugfix, backward-compatible, release-0.10

#1198 Jeremie/notify sql
  crates/client-api/src/routes/database.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/query.rs
  crates/core/src/util/slow.rs
  crates/core/src/vm.rs
  crates/sqltest/src/space.rs
  crates/vm/src/eval.rs
  crates/vm/src/expr.rs
Labels: backward-compatible, release-0.10

#1332 Make both TX offset counters agree
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
Labels: bugfix, backward-compatible, release-0.10

#1346 Fix `Config.save` failing if `/tmp` is on a different filesystem
  Cargo.lock
  crates/fs-utils/Cargo.toml
  crates/fs-utils/src/lib.rs
Labels: release-any, bugfix

#1290 Prune bindings deps
  Cargo.lock
  Cargo.toml
  crates/bindings/Cargo.toml
  crates/bindings/tests/deps.rs
  crates/bindings/tests/snapshots/deps__duplicate_deps.snap
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/core/Cargo.toml
  crates/lib/Cargo.toml
  crates/lib/src/address.rs
  crates/lib/src/identity.rs
  crates/lib/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/ids.rs
  crates/sats/Cargo.toml
  crates/sats/src/hash.rs
Labels: release-any

#1232 Add Jenkinsfile to run internal automation
  .jenkins/Jenkinsfile.internal
Labels: no runtime change, release-0.10

#1305 core: Store address, owner and program bytes in st_module
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/identity.rs
  crates/core/src/database_instance_context.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/host/disk_storage.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/messages/control_db.rs
  crates/durability/src/lib.rs
  crates/sats/src/hash.rs
  crates/standalone/src/control_db.rs
  crates/standalone/src/control_db/tests.rs
  crates/standalone/src/energy_monitor.rs
  crates/standalone/src/lib.rs
  crates/testing/src/modules.rs
  crates/testing/tests/standalone_integration_test.rs
Labels: abi-break, api-break, release-0.10

#1359 Add explicit parameter for table visibility
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Module.cs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
Labels: api-break, release-0.10

#1349 Bump version to 0.10.0
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any

#1344 Integrate snapshotting into core
  Cargo.lock
  crates/core/Cargo.toml
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/error.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/subscription/query.rs
  crates/snapshot/src/lib.rs
  crates/table/src/pages.rs
  crates/table/src/table.rs
Labels: release-0.10

#1360 durability: Skip fsync if nothing changed
  crates/durability/src/imp/local.rs
Labels: release-any

#1405 Add Option SDK tests
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/Codegen.Tests/Sample.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#CustomClass.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#CustomStruct.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_every_primitive_struct_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_i_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_identity_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_simple_enum_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_string_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_option_vec_option_i_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/module_bindings/option_every_primitive_struct.rs
  crates/sdk/tests/test-client/src/module_bindings/option_i_32.rs
  crates/sdk/tests/test-client/src/module_bindings/option_identity.rs
  crates/sdk/tests/test-client/src/module_bindings/option_simple_enum.rs
  crates/sdk/tests/test-client/src/module_bindings/option_string.rs
  crates/sdk/tests/test-client/src/module_bindings/option_vec_option_i_32.rs
  crates/sdk/tests/test-client/src/simple_test_table.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-any, bugfix, api-break

#714 Add small 'realistic' workload benchmark integration test
  crates/bench/README.md
  crates/bench/benches/special.rs
  crates/bench/src/schemas.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/benchmarks/src/circles.rs
  modules/benchmarks/src/ia_loop.rs
  modules/benchmarks/src/lib.rs
  modules/benchmarks/src/synthetic.rs
Labels: release-any, no runtime change

#1343 Impl subscribe subcommand & subscription smoketests
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/api.rs
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/mod.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/fs-utils/src/lockfile.rs
  crates/sats/src/typespace.rs
  crates/standalone/src/lib.rs
  smoketests/__init__.py
  smoketests/tests/permissions.py
Labels: release-any

#1426 Update tools/publish-crates.sh
  tools/publish-crates.sh
Labels: release-any, no runtime change

#1443 Bump version to 0.10.1
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any

#1440 Restructure NuGet packaging
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen.Tests/Codegen.Tests.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Directory.Build.props
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  smoketests/tests/csharp_module.py
Labels: breaks library compatibility, release-0.11

#1367 Smoketest auto-disconnect after restart
  .github/workflows/ci.yml
  smoketests/tests/zz_docker.py
Labels: release-any, no runtime change

#1404 core: Simplify custom bootstrap
  crates/core/src/host/host_controller.rs
Labels: release-any, breaks library compatibility

#1457 CLI - Update help text suggesting `spacetime server fingerprint` to have the correct `-s` param
  crates/cli/src/config.rs
  crates/cli/src/subcommands/identity.rs
Labels: release-any

#735 Fix inconsistent auth/identity creation
  crates/client-api/src/auth.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/energy.rs
  crates/client-api/src/routes/identity.rs
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/auth/identity.rs
  crates/standalone/src/routes/mod.rs
  crates/standalone/src/subcommands/start.rs
Labels: bugfix, breaks library compatibility, release-1.0
