Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-07, with the labels that each got.

#1403 smoketests: Add test for module hotswapping
  smoketests/tests/modules.py
Labels: release-any, no runtime change

#1484 CLI: Put some common params in a central place
  crates/cli/src/common_args.rs
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/delete.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/dns.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/logs.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/server.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/subcommands/tracelog.rs
Labels: CLI only

#1456 Implement a temporary type check validation on sql compiling
  crates/core/src/error.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/mod.rs
  crates/core/src/sql/type_check.rs
  crates/sats/src/sum_type.rs
  crates/vm/src/errors.rs
Labels: reassessing, bugfix, backward-compatible, release-0.11

#1390 Make some commitlog helpers public
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/mem.rs
  crates/commitlog/src/segment.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/mod.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
Labels: release-any

#1035 Adding benchmark for deserialize json & product value
  crates/bench/benches/special.rs
  crates/bench/src/schemas.rs
Labels: release-any, no runtime change

#1482 CLI: Use `--server` and `--identity` args consistently instead of anonymous args
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/identity.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/server.rs
  smoketests/__init__.py
  smoketests/tests/identity.py
Labels: release-any, CLI only, api-break

#1478 Fix running 'cargo test' in crates/lib
  Cargo.toml
Labels: release-any

#1455 Restructure C# SpacetimeDB runtime
  crates/bindings-csharp/.editorconfig
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/BSATN.Runtime/.editorconfig
  crates/bindings-csharp/BSATN.Runtime/Attrs.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN/AlgebraicType.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/bindings-csharp/BSATN.Runtime/Internal/ByteArrayComparer.cs
  crates/bindings-csharp/Codegen.Tests/Codegen.Tests.csproj
  crates/bindings-csharp/Codegen.Tests/Sample.cs
  crates/bindings-csharp/Codegen.Tests/TestInit.cs
  crates/bindings-csharp/Codegen.Tests/Tests.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Reducers.InsertData.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Test.NestingNamespaces.AndClasses.InsertData2.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Exceptions.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/Filter.cs
  crates/bindings-csharp/Runtime/Internal/IReducer.cs
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/Module.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/bindings-csharp/Runtime/bindings.c
  crates/cli/src/subcommands/project/csharp/Lib._cs
  modules/sdk-test-connect-disconnect-cs/Lib.cs
  modules/sdk-test-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/Lib.cs
Labels: breaks library compatibility, api-break, release-0.11

#1499 refactor(1494): Remove SQL DDL per 1.0 SQL spec
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/query.rs
  crates/core/src/vm.rs
  crates/vm/src/expr.rs
Labels: api-break

#1500 C# smoketests use `nuget.config`
  smoketests/tests/csharp_module.py
Labels: release-any, no runtime change

#1503 CI - SpacetimeDB PRs run the C# SDK tests
  .github/workflows/ci.yml
Labels: release-any, no runtime change

#1449 Timer Table Implementation
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/Codegen.Tests/Sample.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PrivateTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Reducers.InsertData.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Test.NestingNamespaces.AndClasses.InsertData2.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Module#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen.Tests/snapshots/Type#Timers.SendMessageTimer.verified.cs
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  crates/bindings-csharp/Runtime/Internal/FFI.cs
  crates/bindings-csharp/Runtime/Internal/IReducer.cs
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings-csharp/Runtime/Internal/Timing.cs
  crates/bindings-csharp/Runtime/Runtime.cs
  crates/bindings-csharp/Runtime/bindings.c
  crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/module.rs
  crates/bindings-sys/src/lib.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/src/timestamp.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  crates/client-api/src/routes/database.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/error.rs
  crates/core/src/execution_context.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/core/src/messages/instance_db_trace_log.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/lib/src/lib.rs
  crates/lib/src/scheduler.rs
  crates/sats/src/db/def.rs
  crates/sats/src/product_type.rs
  crates/sdk/src/lib.rs
  modules/rust-wasm-test/src/lib.rs
  smoketests/tests/cancel_reducer.py
  smoketests/tests/modules.py
Labels: abi-break, release-0.11

#1491 Return empty success from /identity GET
  crates/client-api/src/routes/identity.rs
Labels: release-any, api-break

#1492 Moving recovery code APIs under /identity and using POST
  crates/cli/src/subcommands/identity.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/identity.rs
Labels: release-any, api-break

#1526 `Table::is_row_present`: don't panic
  crates/table/src/table.rs
Labels: bugfix, backward-compatible

#1479 Move `db` module from `spacetimedb_sats` to `spacetimedb_lib`
  Cargo.lock
  crates/bench/benches/special.rs
  crates/bench/src/spacetime_raw.rs
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/generate/python.rs
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/src/subcommands/generate/typescript.rs
  crates/core/src/db/cursor.rs
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/sequence.rs
  crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/db/update.rs
  crates/core/src/error.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/scheduler.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/ast.rs
  crates/core/src/sql/compiler.rs
  crates/core/src/sql/execute.rs
  crates/core/src/sql/type_check.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/lib/Cargo.toml
  crates/lib/src/db/attr.rs
  crates/lib/src/db/auth.rs
  crates/lib/src/db/def.rs
  crates/lib/src/db/error.rs
  crates/lib/src/db/mod.rs
  crates/lib/src/lib.rs
  crates/lib/src/relation.rs
  crates/sats/Cargo.toml
  crates/sats/src/lib.rs
  crates/sats/src/primitives.rs
  crates/table/benches/page_manager.rs
  crates/table/src/btree_index.rs
  crates/table/src/read_column.rs
  crates/table/src/table.rs
  crates/vm/src/errors.rs
  crates/vm/src/eval.rs
  crates/vm/src/expr.rs
  crates/vm/src/rel_ops.rs
  crates/vm/src/relation.rs
  modules/rust-wasm-test/src/lib.rs
Labels: release-any, api-break

#1501 Add some helper scripts
  tools/clippy.sh
  tools/run-all-tests.sh
Labels: release-any

#1528 commitlog: Fix single-commit bitflip test
  crates/commitlog/proptest-regressions/commit.txt
  crates/commitlog/src/commit.rs
Labels: no runtime change, bugfix, backward-compatible

#1531 Bump version to 0.11.0
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any

#1532 ST sequences: respect allocated amount on restart
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/sequence.rs
  crates/core/src/db/datastore/traits.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/vm.rs
  crates/lib/src/db/def.rs
  smoketests/tests/add_remove_index.py
  smoketests/tests/zz_docker.py
Labels: release-any, bitcraft issue, bugfix, backward-compatible

#1441 Don't run bot tests on every master commit whoops
  .github/workflows/bottest.yml
Labels: release-any, no runtime change

#1537 `spacetime generate` - make the source args optional
  crates/cli/src/subcommands/generate/mod.rs
Labels: CLI only, backward-compatible, release-0.11

#1545 C#: ignore fields in partial declaration not marked with BSATN attribute
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Codegen/Utils.cs
  crates/bindings-csharp/Codegen.Tests/Sample.cs
  crates/bindings-csharp/Codegen/Module.cs
Labels: bugfix, release-0.11

#1518 ABI BREAK: Add versioning for RawModuleDef
  crates/bindings-csharp/Runtime/Internal/Module.cs
  crates/bindings/src/rt.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/lib/src/lib.rs
Labels: release-any, abi-break

#1544 core: Start system table ids at 1
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/vm.rs
Labels: release-any

#1557 Remove support for the `update` reducer
  crates/bindings-macro/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/db/update.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/standalone/src/lib.rs
  modules/rust-wasm-test/src/lib.rs
  smoketests/tests/modules.py
Labels: abi-break
