Repository clockworklabs/SpacetimeDB, pull requests merged in 2024-01, with the labels that each got.

#702 spacetime local clear subcommand
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/local.rs
  crates/cli/src/subcommands/mod.rs
Labels: release-0.8.1

#696 Inline typerefs
  crates/core/src/host/wasm_common.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/sats/src/typespace.rs
Labels: release-0.8.1

#701 Print logs to stdout instead of stderr
  crates/cli/src/subcommands/logs.rs
Labels: abi-break, release-0.9

#744 Cleanup SpacetimeDB name usages
  crates/bench/hyper_cmp.py
  crates/cli/src/subcommands/repl.rs
  crates/cli/tools/sublime/SpacetimeDBSQL.sublime-syntax
  crates/sdk/src/background_connection.rs
  crates/sqltest/Cargo.toml
  crates/sqltest/README.md
  crates/sqltest/src/main.rs
  crates/sqltest/src/space.rs
  crates/vm/src/program.rs
Labels: abi-break
