Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-03, with the labels that each got.

#2333 Remove errant backslash that got into the 'please add to path' message
  crates/update/src/cli/self_install.rs
Labels: release-any

#2352 Update bytes_sent_to_clients when merging metrics
  crates/core/src/subscription/module_subscription_actor.rs
  crates/lib/src/metrics.rs
Labels: bugfix

#2242 Support RFC 3339 timestamp values in sql
  Cargo.lock
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  crates/expr/src/check.rs
  crates/expr/src/lib.rs
  crates/lib/Cargo.toml
  crates/sats/Cargo.toml
  crates/sats/src/timestamp.rs
Labels: reassessing

#2359 CLI - Fix `sql --interactive` case where returned rows are 0
  crates/cli/src/subcommands/sql.rs
Labels: CLI only, backward-compatible, release-1.0.1

#2334 Make the `tools/merge-docker-images.sh` script more generic
  .github/workflows/docker.yml
  tools/merge-docker-images.sh
Labels: release-any, no runtime change

#2398 fix: bag semantics for joins
  crates/core/src/subscription/delta.rs
  crates/core/src/subscription/query.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/b_tree_u_32_type.rs
  crates/sdk/tests/test-client/src/module_bindings/btree_u_32_table.rs
  crates/sdk/tests/test-client/src/module_bindings/delete_from_btree_u_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_into_btree_u_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_into_pk_btree_u_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/module_bindings/update_btree_u_32_reducer.rs
  crates/sdk/tests/test.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
  smoketests/tests/add_remove_index.py
Labels: bugfix, release-1.0.1

#2431 Bump versions to 1.0.1
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-1.0.1

#2435 update install instructions in readme
  README.md
Labels: release-any

#2444 Fix outdated advice in `getrandom` warning
  crates/cli/src/tasks/rust.rs
Labels: release-1.0.1

#2409 When generating for typescript, convert the primary key to camel case.
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
Labels: bugfix, backward-compatible, release-1.0.1

#2360 Bring over Rust module doc fixes from the C# module docs
  crates/bindings/README.md
  crates/bindings/src/lib.rs
  crates/bindings/src/table.rs
Labels: documentation, release-any, no runtime change

#2468 commitlog: Fix open flags for read-only offset index
  crates/commitlog/src/index/indexfile.rs
Labels: release-any

#2472 Allow databases from 1.0.1 to be run on 1.0.0
  crates/core/src/config.rs
  crates/standalone/src/lib.rs
Labels: backward-compatible, release-1.0.1

#2418 Build for musl
  .github/workflows/package.yml
Labels: no runtime change, release-1.0.1

#2470 Use jemalloc in standalone and add stats.
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/bench/benches/generic.rs
  crates/bench/benches/special.rs
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/core/Cargo.toml
  crates/core/src/worker_metrics/mod.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/main.rs
  crates/standalone/src/subcommands/start.rs
Labels: backward-compatible, release-1.0.1

#2492 commitlog: Streaming
  Cargo.lock
  Cargo.toml
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commit.rs
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/error.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/mem.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/stream.rs
  crates/commitlog/src/stream/common.rs
  crates/commitlog/src/stream/reader.rs
  crates/commitlog/src/stream/writer.rs
  crates/commitlog/src/tests/bitflip.rs
  crates/commitlog/src/tests/helpers.rs
  crates/commitlog/tests/io.rs
  crates/commitlog/tests/random_payload/mod.rs
  crates/commitlog/tests/streaming/mod.rs
Labels: release-any

#2328 Add .cargo/config.toml to spacetime init Rust project with default target to wasm
  crates/cli/src/subcommands/init.rs
  crates/cli/src/subcommands/project/rust/config._toml
  modules/benchmarks/.cargo/config.toml
  modules/keynote-benchmarks/.cargo/config.toml
  modules/perf-test/.cargo/config.toml
  modules/quickstart-chat/.cargo/config.toml
  modules/sdk-test-connect-disconnect/.cargo/config.toml
  modules/sdk-test/.cargo/config.toml
Labels: release-any, bugfix

#2484 Install tls dependencies in standalone dockerfile
  crates/standalone/Dockerfile
Labels: release-any

#2466 CI - Containerize linux x86_64 GNU builds
  .github/workflows/package.yml
Labels: no runtime change, release-1.0.1

#2462 Print back the # of rows affected (ins, upd, del) with timings
  crates/cli/src/api.rs
  crates/cli/src/subcommands/sql.rs
  crates/client-api/src/lib.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/json/client_api.rs
  crates/core/src/sql/execute.rs
  crates/execution/src/dml.rs
  crates/lib/src/metrics.rs
Labels: release-any

#2531 CI - Make Test Suite check for dirty `git diff`
  .github/workflows/ci.yml
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
Labels: release-any, no runtime change

#2530 commitlog: Open stream writer with metadata
  crates/commitlog/src/stream/writer.rs
Labels: release-any

#2517 Add endpoints for heap profiling
  Cargo.lock
  Cargo.toml
  crates/bench/benches/subscription.rs
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/internal.rs
  crates/client-api/src/routes/mod.rs
  crates/standalone/src/main.rs
Labels: release-any

#2532 Update data size metrics periodically, not on every transaction.
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/replica_context.rs
Labels: release-any, performance

#2504 Commitlog compression
  Cargo.lock
  Cargo.toml
  crates/commitlog/Cargo.toml
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/fs.rs
  crates/commitlog/src/repo/mem.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/stream.rs
  crates/commitlog/src/stream/common.rs
  crates/commitlog/src/stream/reader.rs
  crates/commitlog/src/stream/writer.rs
  crates/commitlog/src/tests/bitflip.rs
  crates/commitlog/src/tests/partial.rs
  crates/commitlog/tests/streaming/mod.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/durability/src/imp/local.rs
  crates/fs-utils/Cargo.toml
  crates/fs-utils/src/compression.rs
  crates/fs-utils/src/lib.rs
  crates/standalone/src/lib.rs
Labels: release-any

#2519 Add utility for rls resolution
  Cargo.lock
  crates/core/src/sql/ast.rs
  crates/expr/Cargo.toml
  crates/expr/src/check.rs
  crates/expr/src/expr.rs
  crates/expr/src/lib.rs
  crates/expr/src/rls.rs
  crates/physical-plan/src/plan.rs
Labels: backward-compatible, release-1.1

#2528 Feature gate #[client_visibility_filter]
  crates/bindings/src/lib.rs
  modules/sdk-test/Cargo.toml
  smoketests/__init__.py
Labels: backward-compatible, release-next
