Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-01, with the labels that each got.

#2054 Tweak scheduled_at macro syntax
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/table.rs
  crates/bindings/tests/ui/reducers.rs
  crates/bindings/tests/ui/reducers.stderr
  modules/rust-wasm-test/src/lib.rs
  modules/sdk-test/src/lib.rs
  smoketests/tests/modules.py
  smoketests/tests/schedule_reducer.py
Labels: breaks library compatibility, release-1.0, api-break

#2030 Server-side implementation of incremental subscription changes
  crates/bench/benches/subscription.rs
  crates/client-api-messages/src/websocket.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/client/message_handlers.rs
  crates/core/src/client/messages.rs
  crates/core/src/error.rs
  crates/core/src/execution_context.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/sdk/src/db_connection.rs
  smoketests/config.toml
Labels: release-any

#2002 Preserve the comments of the "cli.toml" on changes
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/config.rs
  crates/cli/src/errors.rs
  crates/core/Cargo.toml
  crates/core/src/config.rs
Labels: abi-break, release-1.0

#2086 CLI - Confirm before publishing to non-local servers
  crates/cli/src/subcommands/publish.rs
  smoketests/__init__.py
  smoketests/tests/permissions.py
Labels: release-any, CLI only, api-break

#2087 CLI - Fix `spacetime energy balance` not working
  crates/cli/src/subcommands/energy.rs
  smoketests/tests/energy.py
Labels: release-any, CLI only

#2057 Use a spinner to show that wasm is compiling in spacetime generate
  crates/cli/src/subcommands/generate/mod.rs
Labels: release-any

#2046 Enforce .NET 8 SDK for new C# modules
  .github/workflows/benchmarks.yml
  .github/workflows/ci.yml
  crates/cli/src/subcommands/init.rs
  crates/cli/src/subcommands/project/csharp/global._json
  crates/cli/src/tasks/csharp.rs
  modules/global.json
Labels: release-any

#1694 CLI - `dns` subcommand becomes `rename`
  crates/cli/src/lib.rs
  crates/cli/src/subcommands/dns.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/util.rs
  smoketests/tests/domains.py
Labels: release-any, abi-break, CLI only

#2059 Updated version to 1.0.0-rc3
  Cargo.lock
  Cargo.toml
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-any

#2103 Fix defining multiple tables on the same `struct` in Rust modules
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/table.rs
  crates/bindings-macro/src/util.rs
  crates/bindings/src/table.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  modules/rust-wasm-test/src/lib.rs
Labels: bugfix

#2109 Add `SubscriptionBuilder::subscribe_to_all_tables`
  crates/sdk/src/subscription.rs
  crates/sdk/tests/test-client/src/main.rs
Labels: release-any

#2108 commitlog: Make offset index usable externally
  crates/commitlog/src/index/indexfile.rs
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/mod.rs
  crates/commitlog/src/segment.rs
Labels: release-any

#2125 Add new crates to `publish-crates.sh` script
  tools/publish-crates.sh
Labels: release-any, no runtime change

#2105 Rework RLS macro for amended syntax
  Cargo.lock
  crates/bindings-macro/Cargo.toml
  crates/bindings-macro/src/filter.rs
  crates/bindings-macro/src/lib.rs
  crates/bindings/src/client_visibility_filter.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/rt.rs
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
  modules/sdk-test/src/lib.rs
  smoketests/tests/auto_migration.py
Labels: release-1.0, backward-compatible

#2118 Rust SDK: `with_credentials` -> `with_token`
  crates/sdk/examples/quickstart-chat/main.rs
  crates/sdk/src/credentials.rs
  crates/sdk/src/db_connection.rs
  crates/sdk/src/websocket.rs
  crates/sdk/tests/test-client/src/main.rs
Labels: api-break

#2011 Split binaries
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/lib.rs
  crates/cli/src/main.rs
  crates/cli/src/start.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/client-api-messages/src/websocket.rs
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/db/relational_db.rs
  crates/paths/Cargo.toml
  crates/paths/src/cli.rs
  crates/paths/src/lib.rs
  crates/paths/src/utils.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/lib.rs
  crates/standalone/src/subcommands/start.rs
  crates/testing/src/lib.rs
  crates/testing/src/sdk.rs
  crates/update/Cargo.toml
  crates/update/src/main.rs
  crates/update/src/proxy.rs
  smoketests/__main__.py
Labels: release-1.0, backward-compatible

#1928 CLI - Replace clippy with a manual check
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/subcommands/build.rs
  crates/cli/src/tasks/mod.rs
  crates/cli/src/tasks/rust.rs
  crates/testing/src/modules.rs
Labels: release-any, CLI only

#1931 Use actual types for api responses, not ad-hoc `json!()` objects
  Cargo.lock
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/database.rs
  crates/client-api/src/routes/energy.rs
  crates/core/src/messages/control_db.rs
  crates/sats/src/de/serde.rs
  crates/sats/src/lib.rs
  crates/sats/src/ser/serde.rs
Labels: release-any

#2144 Set `tracing` static level for binaries only
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/core/src/database_logger.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/disk_storage.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/util/mod.rs
  crates/standalone/Cargo.toml
  crates/update/Cargo.toml
Labels: release-any

#2143 snapshot: Invalidate newer snapshots on creation
  crates/snapshot/src/lib.rs
Labels: release-1.0, backward-compatible

#2130 Query execution updates for cpu metrics
  crates/execution/src/lib.rs
  crates/execution/src/pipelined.rs
  crates/physical-plan/src/plan.rs
  crates/query/src/delta.rs
  crates/query/src/lib.rs
Labels: release-1.0, backward-compatible

#2146 Fix & test row deletion API
  crates/bindings-csharp/Runtime/Internal/ITable.cs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/delete_large_table_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-1.0, backward-compatible

#2161 Don't create indexes during bootstrapping; wait until after replay
  crates/commitlog/Cargo.toml
  crates/commitlog/src/lib.rs
  crates/commitlog/src/tests.rs
  crates/commitlog/src/tests/helpers.rs
  crates/core/Cargo.toml
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/table/src/table.rs
Labels: bugfix

#2154 Fixed issues with the Rust module quickstart-chat README.md
  modules/quickstart-chat/README.md
Labels: release-any, no runtime change

#2140 Track query and datastore cpu usage metrics
  Cargo.lock
  crates/client-api-messages/src/websocket.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
  crates/core/src/db/datastore/locking_tx_datastore/tx.rs
  crates/core/src/db/db_metrics/mod.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/module_host.rs
  crates/core/src/subscription/delta.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/worker_metrics/mod.rs
  crates/execution/src/pipelined.rs
  crates/lib/src/lib.rs
  crates/lib/src/metrics.rs
  crates/physical-plan/src/plan.rs
  crates/query/src/delta.rs
  crates/query/src/lib.rs
  crates/sats/src/convert.rs
  crates/sats/src/lib.rs
  crates/sats/src/size_of.rs
Labels: release-1.0, backward-compatible

#2158 CLI - Just-in-time login flow
  crates/cli/src/common_args.rs
  crates/cli/src/config.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/delete.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/dns.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/login.rs
  crates/cli/src/subcommands/logs.rs
  crates/cli/src/subcommands/publish.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/util.rs
Labels: CLI only, release-1.0, api-break

#2111 Implement incremental subscriptions on the client
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/sdk/examples/quickstart-chat/main.rs
  crates/sdk/examples/quickstart-chat/module_bindings/identity_connected_reducer.rs
  crates/sdk/examples/quickstart-chat/module_bindings/identity_disconnected_reducer.rs
  crates/sdk/examples/quickstart-chat/module_bindings/init_reducer.rs
  crates/sdk/examples/quickstart-chat/module_bindings/mod.rs
  crates/sdk/src/db_connection.rs
  crates/sdk/src/event.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/spacetime_module.rs
  crates/sdk/src/subscription.rs
  crates/sdk/tests/connect_disconnect_client/src/main.rs
  crates/sdk/tests/connect_disconnect_client/src/module_bindings/identity_connected_reducer.rs
  crates/sdk/tests/connect_disconnect_client/src/module_bindings/identity_disconnected_reducer.rs
  crates/sdk/tests/connect_disconnect_client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test.rs
Labels: release-1.0, backward-compatible
