Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-08, with the labels that each got.

#3102 CI - Remove `bots please`
  .github/workflows/bottest.yml
  .github/workflows/bottest_tracing_fix.patch
Labels: release-any, no runtime change

#3119 Blackholio - Hide generated files from diffs
  demo/Blackholio/client-unity/.gitattributes
Labels: release-any, no runtime change

#3140 C#/Unity SDK - Add some developer docs
  demo/Blackholio/server-rust/src/lib.rs
  sdks/csharp/DEVELOP.md
  sdks/csharp/README.md
Labels: no runtime change

#2956 Enable adding columns in auto migrations in `schema` crate
  crates/bindings-csharp/Runtime/Internal/Autogen/IndexType.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/Lifecycle.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/MiscModuleExport.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawColumnDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawColumnDefaultValueV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDataV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawConstraintDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexAlgorithm.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawIndexDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawMiscModuleExportV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDef.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawModuleDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawReducerDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawRowLevelSecurityDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScheduleDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawScopedTypeNameV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawSequenceDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV8.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawTypeDefV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/RawUniqueConstraintDataV9.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/ReducerDef.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableAccess.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableDesc.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TableType.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/TypeAlias.g.cs
  crates/bindings-csharp/Runtime/Internal/Autogen/Typespace.g.cs
  crates/bindings/tests/ui/tables.stderr
  crates/core/src/db/update.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/sats/src/buffer.rs
  crates/schema/src/auto_migrate.rs
  crates/schema/src/def.rs
  crates/schema/src/def/validate/v9.rs
  crates/schema/src/error.rs
Labels: release-any

#3185 `tools/publish-crates.sh` is more flexible for crate paths
  tools/find-publish-list.py
  tools/publish-crates.sh
Labels: no runtime change

#3012 Smoketests can run against remote servers
  smoketests/__init__.py
  smoketests/__main__.py
  smoketests/config.toml
  smoketests/tests/energy.py
  smoketests/tests/new_user_flow.py
  smoketests/tests/permissions.py
  smoketests/tests/replication.py
  smoketests/tests/servers.py
Labels: release-any, no runtime change

#3193 Fix remaining LICENSE files
  docs/LICENSE.txt
  docs/bsatn/LICENSE
  modules/benchmarks-cs/LICENSE
  modules/benchmarks/LICENSE
  modules/keynote-benchmarks/LICENSE
  modules/module-test-cs/LICENSE
  modules/module-test/LICENSE
  modules/perf-test/LICENSE
  modules/quickstart-chat/LICENSE
  modules/sdk-test-connect-disconnect-cs/LICENSE
  modules/sdk-test-connect-disconnect/LICENSE
  modules/sdk-test-cs/LICENSE
  modules/sdk-test/LICENSE
  sdks/rust/tests/connect_disconnect_client/LICENSE
  sdks/rust/tests/test-client/LICENSE
  sdks/rust/tests/test-counter/LICENSE
  sdks/typescript/packages/sdk/LICENSE.txt
  tools/upgrade-version/LICENSE
Labels: no runtime change
