Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-04, with the labels that each got.

#2486 Update formatting of timestamps and identities in PsqlFormatter
  Cargo.lock
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/cli/src/subcommands/sql.rs
  crates/core/Cargo.toml
  crates/core/src/sql/compiler.rs
  crates/expr/src/lib.rs
  crates/sats/Cargo.toml
  crates/sats/src/product_type.rs
  crates/sats/src/satn.rs
  crates/sats/src/time_duration.rs
  crates/sats/src/timestamp.rs
  modules/sdk-test-cs/Lib.cs
  smoketests/config.toml
  smoketests/tests/sql.py
Labels: release-any, bugfix, CLI only

#2526 Add rls to the sql api
  Cargo.lock
  crates/core/src/sql/execute.rs
  crates/execution/src/pipelined.rs
  crates/expr/Cargo.toml
  crates/expr/src/check.rs
  crates/expr/src/expr.rs
  crates/expr/src/lib.rs
  crates/expr/src/rls.rs
  crates/expr/src/statement.rs
  crates/physical-plan/Cargo.toml
  crates/physical-plan/src/compile.rs
  crates/physical-plan/src/plan.rs
  crates/physical-plan/src/rules.rs
  crates/query/src/lib.rs
  smoketests/tests/rls.py
Labels: backward-compatible, release-1.1

#746 Static feature flag for generating perfmaps
  crates/core/Cargo.toml
  crates/core/src/host/wasmtime/mod.rs
  crates/standalone/Cargo.toml
Labels: release-any

#2502 Various methods and trait impls for time arithmetic
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
  crates/sats/src/time_duration.rs
  crates/sats/src/timestamp.rs
Labels: enhancement, release-any

#2546 Add rls to the subscription api
  crates/bench/benches/subscription.rs
  crates/core/src/estimation.rs
  crates/core/src/host/module_host.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/subscription/subscription.rs
  crates/core/src/vm.rs
  crates/query/src/lib.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/insert_user_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/module_bindings/update_btree_u_32_reducer.rs
  crates/sdk/tests/test-client/src/module_bindings/users_table.rs
  crates/sdk/tests/test-client/src/module_bindings/users_type.rs
  crates/sdk/tests/test.rs
  crates/subscription/src/lib.rs
  modules/sdk-test-cs/Lib.cs
  modules/sdk-test/src/lib.rs
Labels: release-1.1

#2560 Add more subscription stats
  crates/core/src/db/db_metrics/mod.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/replica_context.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: release-any

#2559 snapshot: Remote synchronization
  Cargo.lock
  Cargo.toml
  crates/core/src/db/relational_db.rs
  crates/fs-utils/src/compression.rs
  crates/fs-utils/src/dir_trie.rs
  crates/snapshot/Cargo.toml
  crates/snapshot/src/lib.rs
  crates/snapshot/src/remote.rs
  crates/snapshot/tests/remote.rs
Labels: release-any

#2538 Add integration test for commitlog compression
  crates/commitlog/tests/random_payload/mod.rs
Labels: release-any

#2556 Feature gate [ClientVisibilityFilter] in C#
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/Lib.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
  crates/bindings-csharp/Codegen/Module.cs
  crates/bindings-csharp/Runtime/Attrs.cs
  modules/sdk-test-cs/Lib.cs
Labels: backward-compatible, release-1.1

#2572 Return error for unqualified columns instead of panic
  crates/expr/src/check.rs
  crates/expr/src/statement.rs
  crates/sql-parser/src/ast/sql.rs
  crates/sql-parser/src/ast/sub.rs
Labels: bugfix

#2555 Add some more tokio metrics.
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/worker_metrics/mod.rs
Labels: release-any

#2244 Remove spacetimedb-core as a dep of cli
  Cargo.lock
  Cargo.toml
  crates/auth/Cargo.toml
  crates/auth/src/identity.rs
  crates/auth/src/lib.rs
  crates/cli/Cargo.toml
  crates/cli/src/api.rs
  crates/cli/src/config.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/util.rs
  crates/client-api-messages/src/http.rs
  crates/client-api-messages/src/lib.rs
  crates/client-api/src/lib.rs
  crates/core/Cargo.toml
  crates/core/src/auth/mod.rs
  crates/core/src/auth/token_validation.rs
  crates/core/src/config.rs
  crates/core/src/json/client_api.rs
  crates/core/src/json/control_db.rs
  crates/core/src/json/mod.rs
  crates/core/src/lib.rs
  crates/core/src/sql/compiler.rs
  crates/data-structures/Cargo.toml
Labels: release-any

#2034 Compress the snapshot
  Cargo.lock
  Cargo.toml
  crates/commitlog/src/lib.rs
  crates/commitlog/src/repo/fs.rs
  crates/commitlog/src/stream/common.rs
  crates/core/Cargo.toml
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
  crates/durability/src/imp/local.rs
  crates/fs-utils/src/compression.rs
  crates/fs-utils/src/dir_trie.rs
  crates/fs-utils/src/lockfile.rs
  crates/snapshot/src/lib.rs
  crates/snapshot/src/remote.rs
  crates/snapshot/tests/remote.rs
Labels: release-any

#2585 Impose limits on the heap usage of `ChunkPool`
  crates/core/src/host/instance_env.rs
Labels: release-any

#2521 Make clockworklabs/spacetime docker image build from source
  Dockerfile
Labels: release-any, no runtime change

#2580 Check validity of modules before control DB modifications during initial publish
  crates/client-api/src/routes/database.rs
  crates/core/src/host/host_controller.rs
  crates/standalone/src/lib.rs
  smoketests/tests/fail_initial_publish.py
Labels: release-1.1

#2547 Add docs for `FilterableValue` to rust bindings crate
  crates/bindings-macro/src/sats.rs
  crates/bindings/README.md
  crates/bindings/src/lib.rs
  crates/bindings/tests/ui/tables.stderr
  crates/lib/src/filterable_value.rs
  crates/lib/src/lib.rs
Labels: release-1.1

#2567 Allocate fewer vecs in `eval_updates`
  crates/core/src/subscription/module_subscription_manager.rs
Labels: release-any

#2616 Count bytes_written for updates
  crates/core/src/db/relational_db.rs
  crates/core/src/host/instance_env.rs
Labels: release-1.1.1

#2642 `spacetimedb-update self-install` fails if the install fails.
  crates/update/src/cli/self_install.rs
Labels: release-any

#2645 Do not publish RLS rules on private tables
  crates/core/src/sql/parser.rs
  smoketests/tests/auto_migration.py
  smoketests/tests/fail_initial_publish.py
  smoketests/tests/rls.py
Labels: release-any

#2609 Return the query text with subscription errors
  crates/core/src/error.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: release-any

#2615 Typescript Generation: Wrap union types in parens if for arrays
  crates/cli/src/subcommands/generate/typescript.rs
Labels: release-any

#2636 Implement OnUnhandledReducerError in C#
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
Labels: release-any

#2641 Prune queries from subscription evaluation
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/lib/src/metrics.rs
  crates/physical-plan/src/plan.rs
Labels: release-next

#2654 Remove redundant rows from subscription updates
  crates/core/src/db/db_metrics/mod.rs
  crates/core/src/subscription/delta.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/execution/src/lib.rs
  crates/lib/src/metrics.rs
  crates/subscription/src/lib.rs
Labels: release-next

#2593 Split client codegen out into its own crate
  .github/CODEOWNERS
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/bindings-csharp/Runtime/README.md
  crates/cli/Cargo.toml
  crates/cli/src/subcommands/generate.rs
  crates/cli/src/tasks/csharp.rs
  crates/cli/src/tasks/rust.rs
  crates/codegen/Cargo.toml
  crates/codegen/examples/regen-csharp-moduledef.rs
  crates/codegen/src/code_indenter.rs
  crates/codegen/src/csharp.rs
  crates/codegen/src/lib.rs
  crates/codegen/src/rust.rs
  crates/codegen/src/typescript.rs
  crates/codegen/src/util.rs
  crates/codegen/tests/codegen.rs
  crates/codegen/tests/snapshots/codegen__codegen_csharp.snap
  crates/codegen/tests/snapshots/codegen__codegen_rust.snap
  crates/codegen/tests/snapshots/codegen__codegen_typescript.snap
  crates/schema/Cargo.toml
  crates/schema/tests/ensure_same_schema.rs
Labels: release-any
