Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-02, with the labels that each got.

#2098 Data size SKU for billing
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/db_metrics/data_size.rs
  crates/core/src/db/db_metrics/mod.rs
  crates/sats/src/proptest.rs
  crates/table/src/blob_store.rs
  crates/table/src/btree_index.rs
  crates/table/src/btree_index/key_size.rs
  crates/table/src/page.rs
  crates/table/src/table.rs
Labels: release-1.0, backward-compatible

#2208 Fix multi-column index scan
  crates/physical-plan/src/plan.rs
  crates/physical-plan/src/rules.rs
  crates/schema/src/def.rs
Labels: bugfix, release-1.0

#2126 Finish spacetimedb-update functionality
  Cargo.lock
  Cargo.toml
  crates/cli/src/lib.rs
  crates/cli/src/main.rs
  crates/cli/src/subcommands/generate/mod.rs
  crates/cli/src/subcommands/mod.rs
  crates/cli/src/subcommands/start.rs
  crates/cli/src/subcommands/upgrade.rs
  crates/cli/src/subcommands/version.rs
  crates/cli/src/version.rs
  crates/paths/Cargo.toml
  crates/paths/src/cli.rs
  crates/standalone/src/lib.rs
  crates/standalone/src/main.rs
  crates/standalone/src/subcommands/mod.rs
  crates/standalone/src/subcommands/start.rs
  crates/standalone/src/subcommands/version.rs
  crates/standalone/src/version.rs
  crates/testing/src/lib.rs
  crates/update/Cargo.toml
  crates/update/build.rs
  crates/update/src/cli.rs
  crates/update/src/cli/install.rs
  crates/update/src/cli/link.rs
  crates/update/src/cli/list.rs
  crates/update/src/cli/uninstall.rs
  crates/update/src/cli/upgrade.rs
  crates/update/src/cli/use.rs
  crates/update/src/main.rs
  crates/update/src/proxy.rs
Labels: release-1.0, backward-compatible

#2226 Rework event contexts in C# SDK
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
Labels: abi-break

#1989 Add /health endpoint
  crates/client-api/src/routes/health.rs
  crates/client-api/src/routes/mod.rs
  crates/standalone/src/routes/mod.rs
Labels: release-any

#2227 CLI - Warn when using an unstable command
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/init.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/server.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/util.rs
Labels: release-1.0

#2232 Standardized module names and added module-test-cs based on module-test
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/bindings-csharp/SpacetimeSharpSATS.sln
  crates/cli/tests/codegen.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
  crates/schema/tests/ensure_same_schema.rs
  crates/testing/tests/standalone_integration_test.rs
  modules/module-test-cs/.gitignore
  modules/module-test-cs/Lib.cs
  modules/module-test-cs/README.md
  modules/module-test-cs/module-test-cs.csproj
  modules/module-test-cs/module-test-cs.sln
  modules/module-test/.cargo/config.toml
  modules/module-test/Cargo.toml
  modules/module-test/index.html
  modules/module-test/protobuf/Test.proto
  modules/module-test/src/lib.rs
  modules/spacetimedb-quickstart-cs/Lib.cs
  modules/spacetimedb-quickstart-cs/README.md
  modules/spacetimedb-quickstart/.gitignore
  modules/spacetimedb-quickstart/Cargo.toml
  modules/spacetimedb-quickstart/src/lib.rs
  tools/update-test-snapshots.sh
Labels: release-1.0

#2127 Use Into<String> instead of ToString
  crates/sats/src/hex.rs
  crates/sdk/src/credentials.rs
  crates/sdk/src/db_connection.rs
Labels: breaks library compatibility, release-1.0, api-break

#2238 Fix confusing csharp workload-install error message
  crates/cli/src/tasks/csharp.rs
Labels: release-1.0

#2239 Implement IComparable for Timestamp
  crates/bindings-csharp/BSATN.Runtime.Tests/Tests.cs
  crates/bindings-csharp/BSATN.Runtime/Builtins.cs
Labels: release-1.0

#2181 Remove janky schema from http API
  crates/cli/src/api.rs
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/subscribe.rs
  crates/cli/src/util.rs
  crates/client-api/src/auth.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/sats/src/lib.rs
  crates/sdk/src/websocket.rs
  smoketests/tests/describe.py
  smoketests/tests/permissions.py
Labels: release-1.0, api-break

#2230 DBConnection -> DbConnection for the TypeScript API
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
Labels: abi-break, release-1.0

#2237 CLI - Default config lists maincloud, not testnet
  crates/cli/src/config.rs
Labels: release-1.0

#1966 Remove some Identity conversions that could panic
  crates/core/src/sql/execute.rs
  crates/lib/src/identity.rs
  crates/standalone/src/control_db.rs
  crates/standalone/src/control_db/tests.rs
Labels: release-1.0, api-break

#2229 Implemented error arguments in error callbacks
  crates/cli/src/subcommands/generate/rust.rs
  crates/cli/tests/snapshots/codegen__codegen_rust.snap
  crates/sdk/examples/quickstart-chat/main.rs
  crates/sdk/examples/quickstart-chat/module_bindings/mod.rs
  crates/sdk/src/db_connection.rs
  crates/sdk/src/error.rs
  crates/sdk/src/spacetime_module.rs
  crates/sdk/src/subscription.rs
  crates/sdk/tests/connect_disconnect_client/src/main.rs
  crates/sdk/tests/connect_disconnect_client/src/module_bindings/mod.rs
  crates/sdk/tests/test-client/src/main.rs
  crates/sdk/tests/test-client/src/module_bindings/mod.rs
Labels: release-1.0, api-break

#2248 Only support bearer auth
  crates/client-api/src/auth.rs
Labels: release-1.0

#2250 Fixup comment for SpacetimeCreds
  crates/client-api/src/auth.rs
Labels: release-1.0

#2249 C# SDK - Emit Event.UnknownTransaction rather than throwing on unknown reducer (#2241)
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
Labels: release-1.0

#2247 CI - Update `actions/cache@v2` -> `@v4`
  .github/workflows/docker.yml
Labels: release-any, no runtime change

#2277 CLI - Remove newlines from command helptext
  crates/cli/src/subcommands/call.rs
  crates/cli/src/subcommands/describe.rs
  crates/cli/src/subcommands/energy.rs
  crates/cli/src/subcommands/init.rs
  crates/cli/src/subcommands/list.rs
  crates/cli/src/subcommands/server.rs
  crates/cli/src/subcommands/sql.rs
  crates/cli/src/subcommands/subscribe.rs
Labels: release-any

#2282 Add README.md to all modules in SpacetimeDB/modules describing their usage
  modules/benchmarks-cs/README.md
  modules/benchmarks/README.md
  modules/keynote-benchmarks/README.md
  modules/module-test-cs/README.md
  modules/module-test/README.md
  modules/perf-test/README.md
  modules/quickstart-chat/README.md
  modules/sdk-test-connect-disconnect-cs/README.md
  modules/sdk-test-connect-disconnect/README.md
  modules/sdk-test-cs/README.md
  modules/sdk-test/README.md
Labels: documentation, release-any

#2050 Update Rust module documentation
  crates/bindings-macro/src/lib.rs
  crates/bindings-sys/src/lib.rs
  crates/bindings/README.md
  crates/bindings/bindings-doctests.sh
  crates/bindings/src/client_visibility_filter.rs
  crates/bindings/src/lib.rs
  crates/bindings/src/log_stopwatch.rs
  crates/bindings/src/rng.rs
  crates/bindings/src/rt.rs
  crates/bindings/src/table.rs
  crates/data-structures/src/slim_slice.rs
  crates/lib/src/connection_id.rs
  crates/lib/src/db/raw_def/v8.rs
  crates/lib/src/db/raw_def/v9.rs
  crates/lib/src/identity.rs
  crates/lib/src/lib.rs
  crates/lib/src/operator.rs
  crates/lib/src/relation.rs
  crates/lib/src/scheduler.rs
  crates/sats/src/algebraic_type.rs
  crates/sats/src/algebraic_value/ser.rs
  crates/sats/src/algebraic_value_hash.rs
  crates/sats/src/array_value.rs
  crates/sats/src/bsatn.rs
  crates/sats/src/de.rs
  crates/sats/src/product_type.rs
  crates/sats/src/satn.rs
  crates/sats/src/ser.rs
  crates/sats/src/sum_type.rs
  crates/sats/src/typespace.rs
Labels: release-any, no runtime change

#2265 Update install script
  .github/workflows/package.yml
  Cargo.lock
  crates/paths/src/lib.rs
  crates/update/Cargo.toml
  crates/update/spacetime-install.ps1
  crates/update/spacetime-install.sh
  crates/update/src/cli.rs
  crates/update/src/cli/install.rs
  crates/update/src/cli/self_install.rs
  crates/update/src/cli/upgrade.rs
  crates/update/src/main.rs
Labels: release-1.0, backward-compatible

#2278 Add multi-query version of subscribe messages, and dedup queries on the backend.
  crates/client-api-messages/src/websocket.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/client/message_handlers.rs
  crates/core/src/client/messages.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/sdk/src/db_connection.rs
Labels: release-1.0

#2287 Fix some typos in the ts code gen.
  crates/cli/src/subcommands/generate/typescript.rs
  crates/cli/tests/snapshots/codegen__codegen_typescript.snap
Labels: release-1.0

#2281 Rust client SDK: send `SubscribeMulti` and `UnsubscribeMulti`
  crates/sdk/examples/quickstart-chat/main.rs
  crates/sdk/src/db_connection.rs
  crates/sdk/src/subscription.rs
  crates/sdk/tests/test-client/src/main.rs
Labels: release-1.0

#2295 fix: join order rewrite rule
  crates/core/src/subscription/query.rs
  crates/physical-plan/src/plan.rs
  crates/physical-plan/src/rules.rs
Labels: bugfix, release-1.0

#2259 Clear DB size gauges when shutting a module down
  crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
  crates/core/src/db/db_metrics/data_size.rs
  crates/core/src/host/host_controller.rs
  crates/metrics/src/typed_prometheus.rs
Labels: release-1.0, backward-compatible

#2303 Final C# codegen changes
  crates/cli/src/subcommands/generate/csharp.rs
  crates/cli/tests/snapshots/codegen__codegen_csharp.snap
  crates/sdk/src/subscription.rs
Labels: release-1.0, api-break

#2297 Added in a SQL execution time calculation
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/core/src/json/client_api.rs
Labels: release-1.0

#2309 sdk: Client ping on idle connections
  crates/client-api/src/routes/subscribe.rs
  crates/sdk/src/websocket.rs
Labels: release-1.0

#2294 Fix self-replace on windows
  Cargo.lock
  Cargo.toml
  crates/paths/src/cli.rs
  crates/update/Cargo.toml
  crates/update/src/cli/upgrade.rs
Labels: release-1.0

#2308 hacky auth check for database creation.
  crates/client-api/src/routes/database.rs
Labels: release-1.0

#2310 Update Rust client quickstart example to match tutorial document
  crates/sdk/examples/quickstart-chat/main.rs
Labels: release-any

#2315 Removed the EULA check in the CLI
  crates/update/src/cli/self_install.rs
Labels: release-1.0

#2322 Update `insert` docs to reflect actual behavior on set-semantic duplicates
  crates/bindings/src/table.rs
Labels: release-1.0

#2321 Add link to documentation of SEQUENCES
  crates/bindings/README.md
Labels: documentation

#2319 Add missing LICENSE
  crates/query/LICENSE
  crates/sdk/tests/connect_disconnect_client/Cargo.toml
  crates/sdk/tests/connect_disconnect_client/LICENSE
  crates/sdk/tests/test-client/Cargo.toml
  crates/sdk/tests/test-client/LICENSE
  crates/sdk/tests/test-counter/Cargo.toml
  crates/sdk/tests/test-counter/LICENSE
  crates/subscription/LICENSE
  crates/testing/Cargo.toml
  crates/update/Cargo.toml
  crates/update/LICENSE
  docs/bsatn/LICENSE
  modules/benchmarks-cs/LICENSE
  modules/benchmarks/Cargo.toml
  modules/benchmarks/LICENSE
  modules/keynote-benchmarks/Cargo.toml
  modules/keynote-benchmarks/LICENSE
  modules/module-test-cs/LICENSE
  modules/module-test/Cargo.toml
  modules/module-test/LICENSE
  modules/perf-test/Cargo.toml
  modules/perf-test/LICENSE
  modules/quickstart-chat/Cargo.toml
  modules/quickstart-chat/LICENSE
  modules/sdk-test-connect-disconnect-cs/LICENSE
  modules/sdk-test-connect-disconnect/Cargo.toml
  modules/sdk-test-connect-disconnect/LICENSE
  modules/sdk-test-cs/LICENSE
  modules/sdk-test/Cargo.toml
  modules/sdk-test/LICENSE
  tools/upgrade-version/Cargo.toml
  tools/upgrade-version/LICENSE
Labels: documentation, release-any

#2283 Bump Rust and C# package versions to 1.0.0
  Cargo.lock
  Cargo.toml
  LICENSE.txt
  crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
  crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
  crates/bindings-csharp/Codegen/Codegen.csproj
  crates/bindings-csharp/Runtime/Runtime.csproj
  crates/bindings/README.md
  crates/cli/src/subcommands/project/csharp/StdbModule._csproj
  crates/cli/src/subcommands/project/rust/Cargo._toml
Labels: release-1.0

#2325 set names atomic
  .github/workflows/ci.yml
  crates/client-api-messages/src/name.rs
  crates/client-api/src/lib.rs
  crates/client-api/src/routes/database.rs
  crates/standalone/src/control_db.rs
  crates/standalone/src/control_db/tests.rs
  crates/standalone/src/lib.rs
  smoketests/__init__.py
  smoketests/config.toml
  smoketests/tests/domains.py
  smoketests/tests/permissions.py
Labels: release-1.0
