Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-05, with the labels that each got.

#2688 Reduce allocations in C# when deserializing lists and arrays
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
Labels: release-any, performance

#2705 Fix subscription manager metadata for joins
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: bugfix

#2644 Use spacetimedb-standalone to get schema for spacetime generate
  Cargo.lock
  crates/cli/src/subcommands/generate.rs
  crates/cli/src/subcommands/start.rs
  crates/cli/src/util.rs
  crates/codegen/Cargo.toml
  crates/codegen/src/lib.rs
  crates/codegen/tests/codegen.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/mod.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/schema/Cargo.toml
  crates/schema/tests/ensure_same_schema.rs
  crates/standalone/src/lib.rs
  crates/standalone/src/subcommands/extract_schema.rs
  crates/standalone/src/subcommands/mod.rs
  crates/testing/Cargo.toml
  crates/testing/src/lib.rs
  crates/testing/src/modules.rs
  smoketests/__main__.py
Labels: release-any

#2714 Prevent `ahash` from pulling in `getrandom 0.3`
  Cargo.lock
  Cargo.toml
  crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
Labels: bugfix

#2691 snapshot: Provide streaming snapshot verification.
  Cargo.lock
  crates/snapshot/Cargo.toml
  crates/snapshot/src/lib.rs
  crates/snapshot/src/remote.rs
  crates/snapshot/tests/remote.rs
Labels: release-any

#2728 Fix index scan rewrite rule
  crates/core/src/sql/execute.rs
  crates/physical-plan/src/plan.rs
  crates/physical-plan/src/rules.rs
Labels: bugfix

#2646 Fixed compile errors and warnings on Windows
  crates/bench/benches/generic.rs
  crates/bench/benches/special.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/worker_metrics/mod.rs
  crates/paths/src/lib.rs
  crates/update/src/proxy.rs
Labels: release-any

#2682 Single-threaded subscription evaluation
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: performance, release-next

#2794 Datastore Extraction: TxMetrics refactor, small non-functional change to make datastore extraction easier
  crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
Labels: release-any

#2795 Datastore Extraction: StVarName refactor, small non-functional change in furtherance of datastore extraction
  crates/core/src/db/datastore/system_tables.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/sql/execute.rs
  crates/core/src/vm.rs
Labels: release-any

#2773 Per-database incoming and outgoing queue length metrics
  crates/client-api/src/routes/subscribe.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/worker_metrics/mod.rs
Labels: release-any

#2793 Aggregate and broadcast `DbUpdate`s off the main thread
  crates/client-api-messages/src/websocket.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/instance_env.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/execution_unit.rs
  crates/core/src/subscription/mod.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/core/src/subscription/query.rs
  crates/core/src/worker_metrics/mod.rs
  crates/schema/src/schema.rs
  crates/sqltest/src/space.rs
  crates/subscription/src/lib.rs
Labels: performance, release-next

#2790 core: Make `asyncify` preserve the current span
  crates/core/src/util/mod.rs
Labels: release-any

#2792 commitlog: Fix index truncation test.
  crates/commitlog/src/index/indexfile.rs
  crates/commitlog/src/segment.rs
Labels: release-any
