Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-07, with the labels that each got.

#2910 Record transaction metrics off the main thread
  crates/core/src/db/mod.rs
  crates/core/src/db/relational_db.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/core/src/sql/execute.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
  crates/snapshot/tests/remote.rs
Labels: release-any, performance

#2906 client-api: Rewrite websocket loop
  Cargo.lock
  crates/client-api/Cargo.toml
  crates/client-api/src/routes/subscribe.rs
  crates/client-api/src/util/websocket.rs
  crates/core/src/client.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/client/messages.rs
  crates/core/src/worker_metrics/mod.rs
Labels: release-any

#2935 Add a recursion limit to the evaluation of type_expr & parse_expr
  crates/core/src/error.rs
  crates/core/src/host/module_host.rs
  crates/core/src/sql/execute.rs
  crates/expr/src/errors.rs
  crates/expr/src/lib.rs
  crates/expr/src/statement.rs
  crates/sql-parser/src/parser/errors.rs
  crates/sql-parser/src/parser/mod.rs
  crates/sql-parser/src/parser/recursion.rs
  crates/sql-parser/src/parser/sub.rs
Labels: release-any

#2955 Add React Native support to the Typescript SDK
  sdks/typescript/packages/sdk/package.json
  sdks/typescript/packages/sdk/src/binary_reader.ts
  sdks/typescript/packages/sdk/src/binary_writer.ts
  sdks/typescript/packages/sdk/src/db_connection_impl.ts
  sdks/typescript/pnpm-lock.yaml
Labels: release-any, bugfix
