Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-09, with the labels that each got.

#3195 Unifies TypeScript packages and command names
  .github/workflows/ci.yml
  .github/workflows/docs-validate-nav-build.yml
  .github/workflows/typescript-lint.yml
  .github/workflows/typescript-test.yml
  crates/bindings-typescript/package.json
  crates/bindings-typescript/src/connection_id.ts
  crates/bindings-typescript/src/identity.ts
  docs/.prettierignore
  docs/.prettierrc
  docs/docs/cli-reference.md
  docs/docs/nav.js
  docs/nav.ts
  docs/package.json
  docs/scripts/checkLinks.ts
  docs/scripts/checkNav.mjs
  docs/tools/markdown-fix.mjs
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  sdks/typescript/.github/workflows/cr.yml
  sdks/typescript/.github/workflows/release.yml
  sdks/typescript/examples/quickstart-chat/README.md
  sdks/typescript/examples/quickstart-chat/package.json
  sdks/typescript/examples/quickstart-chat/vitest.config.ts
  sdks/typescript/package.json
  sdks/typescript/packages/sdk/README.md
  sdks/typescript/packages/sdk/package.json
  sdks/typescript/packages/sdk/tests/algebraic_type.test.ts
  sdks/typescript/packages/sdk/tests/serde.test.ts
  sdks/typescript/vitest.config.ts
Labels: release-any

#3226 Tidy up CLI reference generation flow
  docs/README.md
  docs/package.json
  docs/scripts/markdown-fix.mjs
Labels: release-any, no runtime change

#2702 Support for the PG wire protocol
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/cli/src/subcommands/sql.rs
  crates/client-api-messages/src/name.rs
  crates/client-api/src/auth.rs
  crates/client-api/src/routes/database.rs
  crates/client-api/src/util.rs
  crates/core/src/auth/mod.rs
  crates/core/src/messages/control_db.rs
  crates/pg/Cargo.toml
  crates/pg/LICENSE
  crates/pg/README.md
  crates/pg/src/encoder.rs
  crates/pg/src/lib.rs
  crates/pg/src/pg_server.rs
  crates/sats/src/satn.rs
  crates/sats/src/ser.rs
  crates/sats/src/ser/impls.rs
  crates/sats/src/time_duration.rs
  crates/sats/src/timestamp.rs
  crates/standalone/Cargo.toml
  crates/standalone/src/lib.rs
  crates/standalone/src/subcommands/start.rs
  docker-compose.yml
  smoketests/tests/pg_wire.py
Labels: enhancement, release-any, api-break

#3177 rust: `default` macro
  crates/bindings-macro/src/lib.rs
  crates/bindings-macro/src/table.rs
  crates/bindings/src/rt.rs
  crates/bindings/src/table.rs
  modules/module-test/src/lib.rs
Labels: release-any, backward-compatible, release-1.4

#3239 CI - Run unreal tests
  .github/workflows/ci.yml
Labels: release-any, no runtime change

#3259 Remove smoke test check for SSL support, let the defaults works
  smoketests/tests/pg_wire.py
Labels: release-any

#3314 Fix CI breakage by PR #3309
  .github/workflows/ci.yml
Labels: release-next

#3308 Integrate `tools/upgrade-version` into cargo and expand
  .cargo/config.toml
  .github/workflows/upgrade-version-check.yml
  Cargo.lock
  tools/upgrade-version/Cargo.toml
  tools/upgrade-version/src/main.rs
Labels: release-any, no runtime change
