Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-06, with the labels that each got.

#2791 commitlog: Reduce log noise when offset index cannot be used
  crates/commitlog/src/commitlog.rs
  crates/commitlog/src/error.rs
  crates/commitlog/src/segment.rs
  crates/commitlog/src/stream/reader.rs
Labels: release-any

#2738 Log every second a reducer takes to run
  crates/client-api-messages/src/energy.rs
  crates/core/src/host/wasmtime/mod.rs
  crates/core/src/host/wasmtime/wasm_instance_env.rs
  crates/core/src/host/wasmtime/wasmtime_module.rs
Labels: release-any

#2799 Fix typo in the log config toml file
  crates/standalone/config.toml
Labels: release-any

#2821 Remove the lock around the `ClientsMap` in the `SubscriptionManager`
  crates/client-api-messages/src/websocket.rs
  crates/core/src/client/client_connection.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/subscription/module_subscription_actor.rs
  crates/core/src/subscription/module_subscription_manager.rs
Labels: release-any

#2850 Add an HTTP route to get the current `Timestamp`
  crates/client-api/src/routes/mod.rs
  crates/client-api/src/routes/unstable.rs
  smoketests/__init__.py
  smoketests/tests/timestamp_route.py
Labels: release-any

#2819 client-api: Don't debug-print dropped outgoing Ws messages at info
  crates/client-api/src/routes/subscribe.rs
Labels: release-any

#2716 Test subscription updates for dml
  crates/core/src/subscription/module_subscription_actor.rs
  smoketests/tests/dml.py
Labels: release-any, no runtime change

#2762 Improve serialization speed of enums without data in C#
  crates/bindings-csharp/BSATN.Codegen/Type.cs
  crates/bindings-csharp/BSATN.Runtime.Tests/Tests.cs
  crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/client/snapshots/Type#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#TestUniqueNotEquatable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Type#TestUnsupportedType.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
  crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Type#CustomNestedClass.verified.cs
Labels: release-any, performance

#2875 durability: Fix task leak
  crates/durability/src/imp/local.rs
Labels: release-any

#2895 `tools/upgrade-version` updates the Change Date in `LICENSE.txt`
  Cargo.lock
  tools/upgrade-version/Cargo.toml
  tools/upgrade-version/src/main.rs
Labels: release-any, no runtime change
