Repository clockworklabs/SpacetimeDB, pull requests merged in 2025-10, with the labels that each got.

#3321 C# tests - update snapshots
  .github/workflows/csharp-test.yml
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Reducers/ClientConnected.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Reducers/ClientDisconnected.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Reducers/SendMessage.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Reducers/SetName.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/SpacetimeDBClient.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Types/Message.g.cs
  sdks/csharp/examples~/quickstart-chat/client/module_bindings/Types/User.g.cs
  sdks/csharp/tools~/gen-quickstart.sh
Labels: release-1.5

#3320 Improve message error if the port is taken
  crates/standalone/src/subcommands/start.rs
Labels: no runtime change, release-1.5

#3275 core: disconnect clients
  crates/client-api/src/routes/database.rs
  crates/core/src/db/update.rs
  crates/core/src/host/host_controller.rs
  crates/core/src/host/module_host.rs
  crates/core/src/host/wasm_common/module_host_actor.rs
  crates/datastore/src/locking_tx_datastore/mut_tx.rs
Labels: release-any

#3302 Document PG wire format
  docs/docs/nav.js
  docs/docs/sql/pg-wire.md
  docs/nav.ts
Labels: documentation, release-any, no runtime change, release-next

#3301 Smoketest : Hotswap should not disconnect subscribers.
  smoketests/tests/auto_migration.py
Labels: release-any, no runtime change
